### ISSUE TITLE
[BUG] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by gitgayhub** [nicoduj/homebridge-harmony#108]
**Describe the bug**
Updated to 1.0 beta 4, after the 1st restart, plugin will work, but there's a error message 

```
Error - Error retrieving info from hub : Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 90c82d4d-acdb-4de3-a00f-f0c0e2d3c12e-(1)

/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:266
  throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
```
Plugin will continue to work without problem. Shutdown homebridge and try to start homebridge again,  got this error message at startup and homebridge won't continue to work

```
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 90c82d4d-acdb-4de3-a00f-f0c0e2d3c12e
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:266:13)
    at Server._configCachedPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:380:18)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:89:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```
Manfully deleting `accessories` folder solve the problem for a while, but the error loop continue if restarting homebridge

Rolling back to 0.5.5 solve the problem permanently

**Comment by nicoduj** [comment]
Hi, Yes, I mentioned this limitation in the release note. You can only have one platform section with dynamic mode in this beta 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Will need significant work to make this possible again in dynamic platform mode

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gitgayhub** [comment]
> Hi, Yes, I mentioned this limitation in the release note. You can only have one platform section with dynamic mode in this beta

Sorry didn't read the note carefully, I updated to 1.0 beta again and run two instances of homebridge using pm2,  they are working fine now

**Comment by nicoduj** [comment]
No problem :) glad to know it is working with 2 homebridge instances . I will see if I can work on this however for final version but if you encounter any other problem feel free to say ! Thank you for testing 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Bêta updated , config changed ne careful, should support multiple hubs or same hub declared multiple times 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
