### ISSUE TITLE
Plugin loading error

### ISSUE THREAD

**Issue by Vincentkhm** [nicoduj/homebridge-harmony#12]
I have encountered errors of loading the plugin:

[12/28/2018, 12:46:28 PM] ERROR LOADING PLUGIN homebridge-harmony:
[12/28/2018, 12:46:28 PM] /usr/local/lib/node_modules/homebridge-harmony/index.js:29
  );
  

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:22)

      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      

Error: The requested platform 'HarmonyHubWebSocket' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

With the configuration:

"platforms": [
  {
    "platform": "HarmonyHubWebSocket",
    "name": "HarmonyHub",
    "hubIP": "192.168.1.99",
    "showTurnOffActivity" : true,
    "turnOffActivityName" : "AV Off"
  },
  {
    "platform": "HarmonyHubWebSocket",
    "name": "HarmonyHub2",
    "hubIP": "192.168.1.98"
  }
]

**Comment by yungsters** [comment]
Are you running off master? And what version of Node.js are you running? Does it go away when you upgrade?
