### ISSUE TITLE
Plugin Loading Error

### ISSUE THREAD

**Issue by derfx4** [nicoduj/homebridge-harmony#14]
Hello, 

I saw a previous error related to what I have, but did not see a clear resolution. 

I just uninstalled the old HarmonyHub plugin and installed yours using:

sudo npm install -g homebridge-harmony

config.json has:

{
    "platform": "HarmonyHubWebSocket",
    "name": "HarmonyHub",
    "hubIP": "192.168.86.38",
    "showTurnOffActivity" : true,
    "turnOffActivityName" : "HT Off"
  },

Node.js version is
 npm node -v
4.2.0

and I am getting this error when launching HomeBridge:

12/28/2018, 4:08:32 PM] ====================
[12/28/2018, 4:08:32 PM] ERROR LOADING PLUGIN homebridge-harmony:
[12/28/2018, 4:08:32 PM] /usr/lib/node_modules/homebridge-harmony/index.js:29
  );
  ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:72:22)
[12/28/2018, 4:08:32 PM] ====================

Any Thoughts?

**Comment by derfx4** [comment]
Thanks...will work on that next.

Appreciate the response and the work on this project!!

**Comment by nicoduj** [comment]
Keep me posted :) I had to upgrade the dependency since I am using request package that depends on it . You might try earlier version of the plugin (0.0.5 I think) but not sure everything will work as expected !

**Comment by derfx4** [comment]
That fixed it.  Moved to new Node. Worked like a charm !! Thanks again!

Closing issue.
