### ISSUE TITLE
[BUG] Renaming platform causes crash on initialization

### ISSUE THREAD

**Issue by Garywoo** [nicoduj/homebridge-harmony#156]
**Describe the bug**
Renaming my `name` config value from anything other than _Harmony Hub_ causes the plugin to crash during Homebridge initialization. The following is seen in the log output:

```
0|homebridge  | TypeError: Cannot read property 'name' of undefined
0|homebridge  |     at HarmonyPlatform.configureAccessory (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/homebridge-harmony/harmonyPlatform.js:101:69)
0|homebridge  |     at Server._configCachedPlatformAccessories (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/homebridge/lib/server.js:386:24)
0|homebridge  |     at Server.run (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/homebridge/lib/server.js:93:8)
0|homebridge  |     at module.exports (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/homebridge/lib/cli.js:59:10)
0|homebridge  |     at Object.<anonymous> (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/homebridge/bin/homebridge:17:22)
0|homebridge  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|homebridge  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|homebridge  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|homebridge  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|homebridge  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|homebridge  |     at Object.<anonymous> (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/pm2/lib/ProcessContainerFork.js:48:21)
0|homebridge  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|homebridge  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|homebridge  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|homebridge  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|homebridge  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|homebridge  |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
0|homebridge  |     at startup (internal/bootstrap/node.js:283:19)
0|homebridge  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
0|homebridge  | [8/14/2019, 7:24:45 PM] TypeError: Cannot read property 'name' of undefined
0|homebridge  |     at HarmonyPlatform.configureAccessory (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/homebridge-harmony/harmonyPlatform.js:101:69)
0|homebridge  |     at Server._configCachedPlatformAccessories (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/homebridge/lib/server.js:386:24)
0|homebridge  |     at Server.run (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/homebridge/lib/server.js:93:8)
0|homebridge  |     at module.exports (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/homebridge/lib/cli.js:59:10)
0|homebridge  |     at Object.<anonymous> (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/homebridge/bin/homebridge:17:22)
0|homebridge  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|homebridge  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|homebridge  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|homebridge  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|homebridge  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|homebridge  |     at Object.<anonymous> (/home/pi/.nvm/versions/node/v10.16.2/lib/node_modules/pm2/lib/ProcessContainerFork.js:48:21)
0|homebridge  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|homebridge  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|homebridge  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|homebridge  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|homebridge  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|homebridge  |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
0|homebridge  |     at startup (internal/bootstrap/node.js:283:19)
0|homebridge  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```

**Reproduce**
I upgraded to 1.0.0, and made the appropriate config migration changes. I was previously using the switches mode, but accepted the new default to use the TV mode. I then realised I should rename the platform as the TV accessory had the name _Harmony Hub_, and I wanted to to be _Living Room TV_ instead. I renamed the `name` config value and restarted Homebridge, but the plugin caused it to crash during initialization.

**Expected behavior**
I would expect the `name` value to work correctly and rename my TV accessory with no errors.

**iOS**
- Version 12.4
- Device: iPhone 6s

**Config**
```
{
    "platform": "HarmonyHubWebSocket",
    "name": "Living Room TV",
    "hubIP": "192.168.2.2",
    "showTurnOffActivity": false,
    "publishSwitchActivitiesAsIndividualAccessories": true,
    "publishDevicesAsIndividualAccessories": true,
    "publishHomeControlsAsIndividualAccessories": true,
    "mainActivity": "Watch Apple TV"
}
```

**Comment by nicoduj** [comment]
are you talking about platform key or name key ? once added, if you change the name, you chould clean your cache I think. 
platform can't be changed.

**Comment by Garywoo** [comment]
I'm talking about the name key, which is described in the readme as:

> `name` is the name of the published accessory (required).

How would you recommend cleaning my cache?

**Comment by nicoduj** [comment]
you can use the option cleanCache of the plugin, or delete the persist folder (but will affect all your homebridge) . So try cleancache option first.

(you must remove for the next restart, otherwise it will clean at each launch, generate new accesories and thus mess your scene / automations)

**Comment by Garywoo** [comment]
Ahh thanks. I set the `cleanCache` option to _true_ and restarted Homebridge. I then set `cleanCache` to _false_ and restarted again. I then renamed the `name` value and restarted again, but the plugin is still crashing on startup. 😥

**Comment by nicoduj** [comment]
correct way to do is :
cleancache to true
restart
stop
cleancache to false
rename
start

**Comment by Garywoo** [comment]
Thanks for this. Following those steps exactly allowed Homebridge to start after `name` was renamed without error.
