### ISSUE TITLE
Merge of 0.7 and 1.0

### ISSUE THREAD

**Issue by Phoenix-DH** [nicoduj/homebridge-harmony#158]
Hey,

until today I had 2 instances running ... one for 0.7 with normal mode and one for TV mode:
```
        {
            "platform": "HarmonyHubWebSocket",
            "name": "HarmonyHub",
            "hubIP": "192.168.XXX.XXX",
            "showTurnOffActivity": "inverted",
            "devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV;PowerOn",
                "Beleuchtung TV;PowerOff",
                "Yamaha AVR;VolumeUp",
                "Yamaha AVR;VolumeDown",
                "Beleuchtung Theke;PowerToggle"
            ]
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Media",
            "hubIP": "192.168.XXX.XXX",
            "TVPlatformMode": true,
            "mainActivity": "Apple TV",
            "numberOfCommandsSentForVolumeControl": 4
        },
```

Today I merged it to one after the upgrad, but it won't work:
```
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Media",
            "hubIP": "192.168.XX.XXX",
            "TVPlatformMode": true,
            "mainActivity": "Apple TV",
            "switchAccessories": true,
            "showTurnOffActivity": "inverted",
            "devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV;PowerOn",
                "Beleuchtung TV;PowerOff",
                "Yamaha AVR;VolumeUp",
                "Yamaha AVR;VolumeDown",
                "Beleuchtung Theke;PowerToggle"
            ],
            "numberOfCommandsSentForVolumeControl": 4
        },
```

Did I miss something or does it just notr work.
My goal is to have all single switches back again, I need them for my automations ...

Thanks.

iOS and homebridge are latest. homebridge-harmony is latest prod version. Or do I have to use another one?

**Comment by nicoduj** [comment]
Hi, I will check asap. Are the turnOffSwitch / devices switch there ? Only activities switch are missing ? Did you clean your homebridge cache ?

**Comment by Phoenix-DH** [comment]
All missing....
Now the bridge is cxrashing ....
You mean cleaning with the switch to do it?

**Comment by nicoduj** [comment]
try the following sequence : 
option cleancache to true in the config
restart homebridge
stop homebridge
cleancache to false
start again

**Comment by Phoenix-DH** [comment]
will add "cleancache": true to it and try.

**Comment by Phoenix-DH** [comment]
At the moment it is like I said, homebridge crashing:
```
Aug 15 18:03:08 phoenixpi homebridge[29292]: [2019-8-15 18:03:08] [Media] INFO - shutdown
Aug 15 18:03:08 phoenixpi homebridge[29292]: [2019-8-15 18:03:08] TypeError: platform.harmonyBase.harmony.end is not a function
Aug 15 18:03:08 phoenixpi homebridge[29292]:     at HarmonyPlatform.<anonymous> (/usr/lib/node_modules/homebridge-harmony/harmonyPlatform.js:60:42)
Aug 15 18:03:08 phoenixpi homebridge[29292]:     at API.emit (events.js:193:13)
Aug 15 18:03:08 phoenixpi homebridge[29292]:     at process.<anonymous> (/usr/lib/node_modules/homebridge/lib/cli.js:48:19)
Aug 15 18:03:08 phoenixpi homebridge[29292]:     at process.emit (events.js:193:13)
```

**Comment by nicoduj** [comment]
I really think your cache is messed up. If cleancach does not work, delete files in perist folder and try again.

The following works for me, which seems pretty the same : 

```json
   "platforms": [
        {
            "DEVMODE" : true,
            "platform": "HarmonyHubWebSocket",
            "name": "NicoHarmonyHub",
            "hubIP": "192.168.1.42",
            "mainActivity": "La TV",
            "switchAccessories": true,
            "showTurnOffActivity": "inverted",
            "devicesToPublishAsAccessoriesSwitch": [
                "Caisson"
            ],
            "numberOfCommandsSentForVolumeControl": 4
        }
```

Log : 
```
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Adding Accessory : NicoHarmonyHub-DEVTV
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - configuring Main TV Service
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Creating TV Service
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - accessories : main activity name : DEVLa TV
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - accessories : activity to configure : DEVVinyl
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Creating Input Service - DEVVinyl
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - accessories : activity to configure : DEVLa PS4
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Creating Input Service - DEVLa PS4
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - accessories : activity to configure : DEVLa Switch
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Creating Input Service - DEVLa Switch
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - accessories : activity to configure : DEVLa TV
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Configuring Main Activity DEVLa TV
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Creating TV Speaker Service
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Creating Input Service - DEVLa TV
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - accessories : activity to configure : DEVUn Film
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Creating Input Service - DEVUn Film
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - accessories : activity to configure : DEVLa musique
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Creating Input Service - DEVLa musique
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Adding Accessory : NicoHarmonyHub-DEVVinyl
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Discovered Activity : DEVVinyl
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Creating Switch Service DEVVinyl/DEVVinyl
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Adding Accessory : NicoHarmonyHub-DEVLa PS4
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Discovered Activity : DEVLa PS4
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Creating Switch Service DEVLa PS4/DEVLa PS4
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Adding Accessory : NicoHarmonyHub-DEVPowerOff
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Discovered Activity : DEVPowerOff
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Creating Switch Service DEVPowerOff/DEVPowerOff
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Adding Accessory : NicoHarmonyHub-DEVLa Switch
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Discovered Activity : DEVLa Switch
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Creating Switch Service DEVLa Switch/DEVLa Switch
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Adding Accessory : NicoHarmonyHub-DEVLa TV
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Discovered Activity : DEVLa TV
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Creating Switch Service DEVLa TV/DEVLa TV
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Adding Accessory : NicoHarmonyHub-DEVUn Film
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Discovered Activity : DEVUn Film
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Creating Switch Service DEVUn Film/DEVUn Film
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Adding Accessory : NicoHarmonyHub-DEVLa musique
[15/08/2019 à 18:02:14] [NicoHarmonyHub] (NicoHarmonyHub)INFO - Discovered Activity : DEVLa musique
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Creating Switch Service DEVLa musique/DEVLa musique
[15/08/2019 à 18:02:14] [NicoHarmonyHub] WARNING - setupFoundAccessories - TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Loading devices...
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Discovered Device : DEVCaisson
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Activating  PowerToggle for DEVCaisson
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Adding Accessory : NicoHarmonyHub-DEVCaisson-PowerToggle
[15/08/2019 à 18:02:14] [NicoHarmonyHub] INFO - Creating Switch Service DEVCaisson/DEVCaisson-PowerToggle
```

**Comment by Phoenix-DH** [comment]
I have to try after homebridge is working again .... Thank you for the quick support....

**Comment by nicoduj** [comment]
clean your persist folder it should be ok :)

**Comment by Phoenix-DH** [comment]
Service won't start anymore .... Don't know why

**Comment by Phoenix-DH** [comment]
Aug 15 18:33:27 phoenixpi homebridge[14531]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
Aug 15 18:33:27 phoenixpi homebridge[14531]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Aug 15 18:33:27 phoenixpi homebridge[14531]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Aug 15 18:33:27 phoenixpi homebridge[14531]:     at Module._compile (internal/modules/cjs/loader.js:816:30)
Aug 15 18:33:27 phoenixpi homebridge[14531]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
Aug 15 18:33:27 phoenixpi homebridge[14531]:     at Module.load (internal/modules/cjs/loader.js:685:32)
Aug 15 18:33:27 phoenixpi homebridge[14531]:     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
Aug 15 18:33:27 phoenixpi homebridge[14531]:     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Aug 15 18:33:27 phoenixpi homebridge[14531]:     at internal/main/run_main_module.js:21:11

Strange ... do not know what now happened ... only restarted the bridge ....
This is not from the plugin, right?

**Comment by nicoduj** [comment]
don't see any log plugin related, you can still try to remove the plugin conf and the plugin from the pluigin directory to check. Do you have the beginning of the error ?

**Comment by Phoenix-DH** [comment]
no... how can I see all the errors?
I will also tryx to reinstall/remove plugins....

**Comment by nicoduj** [comment]
@Phoenix-DH any luck in restoring your homebridge ?

**Comment by Phoenix-DH** [comment]
Still on my way ... have to create all new .. rooms ... will try again the next days

**Comment by nicoduj** [comment]
ok, let me know if there is any problem . D'ont really see why the plugin would have corrupt your homebridge but sorry if it is the case.

**Comment by Phoenix-DH** [comment]
Can‘t imagine ... everything working again ...
Will check next days and let you know.

**Comment by nicoduj** [comment]
Glad to here ! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
