### ISSUE TITLE
[BUG] "View TV Settings" causes HomeBridge crash

### ISSUE THREAD

**Issue by b-** [nicoduj/homebridge-harmony#207]
**Describe the bug**
Upon pressing the "View TV Settings" button under the TV object in the Home app, the homebridge-harmony module doesn't handle the event and Homebridge as a whole crashes.

**To Reproduce**
Press the "View TV Settings" button.

**Expected behavior**
Currently: given that this is caused because the button isn't handled in the first place, I'd expect it to log this and continue on chuggin'. Future, perhaps we could solve some way to interact with the TV's settings menu and use this button to trigger something.

**Screenshots**
![image](https://user-images.githubusercontent.com/284789/69688420-00a15a00-1094-11ea-838e-e1c5e369fd3b.png)

**IOS (please complete the following information):**
- Version 13.3 (17C5046a)
- Device: iPhone X

**Logs**
```
[11/26/2019, 9:34:59 PM] [HubName] (HubName)INFO - SET Characteristic.PowerModeSelection : 0
[11/26/2019, 9:34:59 PM] TypeError: Cannot read property 'SetupCommand' of undefined
    at HarmonySubPlatform.<anonymous> (/root/.nvm/versions/node/v11.14.0/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:1151:39)
    at Characteristic.emit (events.js:193:13)
    at Characteristic.setValue (/root/.nvm/versions/node/v11.14.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/root/.nvm/versions/node/v11.14.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/root/.nvm/versions/node/v11.14.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:193:13)
    at HAPServer._handleCharacteristics (/root/.nvm/versions/node/v11.14.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/root/.nvm/versions/node/v11.14.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:193:13)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[11/26/2019, 9:34:59 PM] Got SIGTERM, shutting down Homebridge...
[11/26/2019, 9:34:59 PM] [HubName] INFO - shutdown
```

**Config**
```json
        {
            "name": "HubName",
            "hubIP": "192.168.1.81",
            "cleanCache": false,
            "mainActivity": "Watch Apple TV",
            "publishGeneralMuteSwitch": true,
            "showCommandsAtStartup": true,
            "platform": "HarmonyHubWebSocket"
        },
```

**Comment by nicoduj** [comment]
Hi, sorry for late answer. I see where the bug is, will fix asap
