### ISSUE TITLE
Starting activity throws js error

### ISSUE THREAD

**Issue by ishockwave** [nicoduj/homebridge-harmony#22]
I can see my activities, so the readout works. Altough upon switching one on, I get the follwoing error in my log
```
Jan 09 19:17:29 deodsrv001 homebridge[14084]: Uncaught exception error:  TypeError: Cannot read property 'includes' of undefined
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at HarmonyPlatform.<anonymous> (/usr/lib/node_modules/homebridge-harmony/index.js:460:44)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at Characteristic.On.emit (events.js:188:13)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at Array.forEach (<anonymous>)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at HAPServer.emit (events.js:188:13)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at IncomingMessage.emit (events.js:188:13)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at endReadableNT (_stream_readable.js:1129:12)
Jan 09 19:17:29 deodsrv001 homebridge[14084]:     at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by nicoduj** [comment]
Hi,

the problem is that this option was mandatory and not specified so . 
it is no more in latest version : 
https://github.com/nicoduj/homebridge-harmony/releases/tag/0.0.9
