### ISSUE TITLE
[BUG] Multiple Hubs : autoDiscovery not working

### ISSUE THREAD

**Issue by donavanbecker** [nicoduj/homebridge-harmony#245]
**Describe the bug**
Homebridge loop when trying to do multiple hubs

**To Reproduce**
Add second hub with dynamic discovery.

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
- Plugin Version 1.3.3

**Logs**
Your log in debug mode (-D option)
```
[4/5/2020, 12:57:47 PM] [HB Supervisor] Restarting Homebridge...
[4/5/2020, 12:57:47 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D -R
[4/5/2020, 12:57:47 PM] [HB Supervisor] Started Homebridge with PID: 74646
[4/5/2020, 12:57:47 PM] Loaded config.json with 0 accessories and 3 platforms.
[4/5/2020, 12:57:47 PM] ---
[4/5/2020, 12:57:47 PM] Loaded plugin: homebridge-config-ui-x
[4/5/2020, 12:57:47 PM] Registering platform 'homebridge-config-ui-x.config'
[4/5/2020, 12:57:47 PM] ---
[4/5/2020, 12:57:47 PM] Loaded plugin: homebridge-dyson-pure-cool
[4/5/2020, 12:57:47 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
[4/5/2020, 12:57:47 PM] ---
[4/5/2020, 12:57:47 PM] Loaded plugin: homebridge-harmony
[4/5/2020, 12:57:47 PM] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
[4/5/2020, 12:57:47 PM] ---
[4/5/2020, 12:57:47 PM] Loading 3 platforms...
[4/5/2020, 12:57:47 PM] [Config] Initializing config platform...
[4/5/2020, 12:57:47 PM] [Config] Running in Service Mode
[4/5/2020, 12:57:47 PM] [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform...
[4/5/2020, 12:57:47 PM] [DysonPureCoolPlatform] Homebridge API available.
[4/5/2020, 12:57:47 PM] [Family Room TV] Initializing HarmonyHubWebSocket platform...
[4/5/2020, 12:57:47 PM] [Family Room TV] HarmonyPlatform Init
[4/5/2020, 12:57:47 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 12:57:47 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 12:57:47 PM] [Family Room TV] (Family Room TV)(Family Room TV)INFO - playPause option set to false
[4/5/2020, 12:57:47 PM] [Family Room TV] (Family Room TV)INFO - input names file does not exist
[4/5/2020, 12:57:47 PM] [Family Room TV] (Family Room TV)INFO - input visibility file does not exist
[4/5/2020, 12:57:47 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 12:57:47 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 12:57:47 PM] [Family Room TV] (Living Room TV)(Living Room TV)INFO - playPause option set to false
[4/5/2020, 12:57:47 PM] [Family Room TV] (Living Room TV)INFO - input names file does not exist
[4/5/2020, 12:57:47 PM] [Family Room TV] (Living Room TV)INFO - input visibility file does not exist
[4/5/2020, 12:57:47 PM] Loading 0 accessories...
[4/5/2020, 12:57:47 PM] [Family Room TV] WARNING - configureAccessory - The platform Downstairs Harmony Hub is not there anymore in your config (name property). It won't be loaded and will be removed from cache.
Setup Payload:
X-HM://00250T3G5AJI7
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 938-50-293 │     
    └────────────┘     
                       
[4/5/2020, 12:57:47 PM] [DysonPureCoolPlatform] Cached accessories loaded.
[4/5/2020, 12:57:47 PM] [DysonPureCoolPlatform] Signing in.
[4/5/2020, 12:57:47 PM] [Family Room TV] DidFinishLaunching
[4/5/2020, 12:57:47 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 12:57:47 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 12:57:47 PM] Homebridge is running on port 51910.
[4/5/2020, 12:57:47 PM] Error: listen EADDRINUSE: address already in use :::61991
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at ResponseCollector.start (/usr/local/lib/node_modules/homebridge-harmony/node_modules/harmonyhubjs-discover/lib/responseCollector.js:33:6)
    at Explorer.start (/usr/local/lib/node_modules/homebridge-harmony/node_modules/harmonyhubjs-discover/lib/explorer.js:74:26)
    at HarmonyBase.discoverHub (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:167:21)
    at HarmonyBase.configureAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:188:12)
    at HarmonyPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/harmonyPlatform.js:78:32)
    at API.emit (events.js:323:22)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:103:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
[4/5/2020, 12:57:47 PM] Got SIGTERM, shutting down Homebridge...
[4/5/2020, 12:57:47 PM] [Family Room TV] INFO - shutdown
[4/5/2020, 12:57:48 PM] [DysonPureCoolPlatform] Signed in.
```
**Config**
Your config section of platform. Please do not post your whole config and especially with logins / passwords !
```
{
            "name": "Family Room TV",
            "hubName": "Family Room TV",
            "otherPlatforms": [
                {
                    "name": "Living Room TV",
                    "hubName": "Living Room TV"
                }
            ],
            "platform": "HarmonyHubWebSocket"
        }
```

**Additional context**

**Comment by nicoduj** [comment]
Thank you for reporting, indeed it can't work the way I did it :( don't have multiple hubs, so blind coding, but it was a miss. Will try to fix that, sorry for the inconvenience.

**Comment by donavanbecker** [comment]
@nicoduj you are totally fine! Thanks for working on implementing this!!!

**Comment by nicoduj** [comment]
@donavanbecker I have pushed some changes on Dynamic-Platform Branch of this repo (default branch), would you mind testing with it before I release to NPM ? Otherwise I will do a beta npm release this week, but I don't want to release to mainstream with no testing :) 

It would be nice if you could check the following : 

1. config of 2 hubs, without any option (no IP, no name for both) -> should log an error, no hub discovered 
2. config of 2 hubs, one with an IP, one without any option (no IP, no name) -> should log an error for second one, first should work,
3. config of 2 hubs, one with a correct name, one without any option -> same as 2),
4. config of 2 hubs, both with a name -> should work :) 
5. if you have some time, tou can also try with a bad name for one hub.

Thank you !

**Comment by donavanbecker** [comment]
Will do!

**Comment by donavanbecker** [comment]
I can do that, and report back.

**Comment by donavanbecker** [comment]
Plugin with No Config.
```
[4/5/2020, 3:42:28 PM] [homebridge-harmonyHub.HarmonyHubWebSocket] HarmonyPlatform Init
[4/5/2020, 3:42:28 PM] [homebridge-harmonyHub.HarmonyHubWebSocket] No configuration found for homebridge-harmonyHub
Setup Payload:
X-HM://00250T3G5AJI7
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 938-50-293 │     
    └────────────┘     
                       
[4/5/2020, 3:42:28 PM] [DysonPureCoolPlatform] Signing in.
[4/5/2020, 3:42:28 PM] Homebridge is running on port 51910.
[4/5/2020, 3:42:29 PM] [DysonPureCoolPlatform] Signed in.
[4/5/2020, 3:42:30 PM] [DysonPureCoolPlatform] Got devices from the Dyson API.
```

**Comment by donavanbecker** [comment]
Config with Plugin with Hub `name` but no `hubname`
```
        {
            "name": "Family Room TV",
            "otherPlatforms": [
                {
                    "name": "Living Room TV"
                }
            ],
            "platform": "HarmonyHubWebSocket"
        }
```
Log
```
[4/5/2020, 3:55:06 PM] [Family Room TV] Initializing HarmonyHubWebSocket platform...
[4/5/2020, 3:55:06 PM] [Family Room TV] HarmonyPlatform Init
[4/5/2020, 3:55:06 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 3:55:06 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 3:55:06 PM] [Family Room TV] (Family Room TV)(Family Room TV)INFO - playPause option set to false
[4/5/2020, 3:55:06 PM] [Family Room TV] (Family Room TV)INFO - input names file does not exist
[4/5/2020, 3:55:06 PM] [Family Room TV] (Family Room TV)INFO - input visibility file does not exist
[4/5/2020, 3:55:06 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 3:55:06 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 3:55:06 PM] [Family Room TV] (Living Room TV)(Living Room TV)INFO - playPause option set to false
[4/5/2020, 3:55:06 PM] [Family Room TV] (Living Room TV)INFO - input names file does not exist
[4/5/2020, 3:55:06 PM] [Family Room TV] (Living Room TV)INFO - input visibility file does not exist
[4/5/2020, 3:55:06 PM] Loading 0 accessories...
Setup Payload:
X-HM://00250T3G5AJI7
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 938-50-293 │     
    └────────────┘     
                       
[4/5/2020, 3:55:06 PM] [DysonPureCoolPlatform] Cached accessories loaded.
[4/5/2020, 3:55:06 PM] [DysonPureCoolPlatform] Signing in.
[4/5/2020, 3:55:06 PM] [Family Room TV] DidFinishLaunching
[4/5/2020, 3:55:06 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 3:55:06 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 3:55:06 PM] Homebridge is running on port 51910.
```

**Comment by donavanbecker** [comment]
config of 2 hubs, one with an IP, one without any option (no IP, no name) -> should log an error for second one, first should work,
```
        {
            "name": "Family Room TV",
            "hubIP": "192.168.7.62",
            "otherPlatforms": [
                {
                    "name": "Living Room TV"
                }
            ],
            "platform": "HarmonyHubWebSocket"
        }
```

**Comment by donavanbecker** [comment]
3. config of 2 hubs, one with a correct name, one without any option -> same as 2),
```
        {
            "name": "Family Room TV",
            "hubName": "Family Room TV",
            "otherPlatforms": [
                {
                    "name": "Living Room TV"
                }
            ],
            "platform": "HarmonyHubWebSocket"
        }
```
Log
```
[4/5/2020, 4:07:49 PM] [Family Room TV] HarmonyPlatform Init
[4/5/2020, 4:07:49 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 4:07:49 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 4:07:49 PM] [Family Room TV] (Family Room TV)(Family Room TV)INFO - playPause option set to false
[4/5/2020, 4:07:49 PM] [Family Room TV] (Family Room TV)INFO - input names file does not exist
[4/5/2020, 4:07:49 PM] [Family Room TV] (Family Room TV)INFO - input visibility file does not exist
[4/5/2020, 4:07:49 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 4:07:49 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 4:07:49 PM] [Family Room TV] (Living Room TV)(Living Room TV)INFO - playPause option set to false
[4/5/2020, 4:07:49 PM] [Family Room TV] (Living Room TV)INFO - input names file does not exist
[4/5/2020, 4:07:49 PM] [Family Room TV] (Living Room TV)INFO - input visibility file does not exist
[4/5/2020, 4:07:49 PM] Loading 0 accessories...
Setup Payload:
X-HM://00250T3G5AJI7
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 938-50-293 │     
    └────────────┘     
                       
[4/5/2020, 4:07:49 PM] [DysonPureCoolPlatform] Cached accessories loaded.
[4/5/2020, 4:07:49 PM] [DysonPureCoolPlatform] Signing in.
[4/5/2020, 4:07:49 PM] [Family Room TV] DidFinishLaunching
[4/5/2020, 4:07:49 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 4:07:49 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 4:07:49 PM] Homebridge is running on port 51910.
```

None Working
<img width="1010" alt="Screen Shot 2020-04-05 at 4 03 58 PM" src="https://user-images.githubusercontent.com/9875439/78509988-ae65f900-7757-11ea-8339-1c94ff1b5651.png">

**Comment by donavanbecker** [comment]
4.config of 2 hubs, both with a name -> should work :)
```
        {
            "name": "Family Room TV",
            "hubName": "Family Room TV",
            "otherPlatforms": [
                {
                    "name": "Living Room TV",
                    "hubName": "Living Room TV"
                }
            ],
            "platform": "HarmonyHubWebSocket"
        }
```
Log
```
[4/5/2020, 4:09:32 PM] [Family Room TV] Initializing HarmonyHubWebSocket platform...
[4/5/2020, 4:09:32 PM] [Family Room TV] HarmonyPlatform Init
[4/5/2020, 4:09:32 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 4:09:32 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 4:09:32 PM] [Family Room TV] (Family Room TV)(Family Room TV)INFO - playPause option set to false
[4/5/2020, 4:09:32 PM] [Family Room TV] (Family Room TV)INFO - input names file does not exist
[4/5/2020, 4:09:32 PM] [Family Room TV] (Family Room TV)INFO - input visibility file does not exist
[4/5/2020, 4:09:32 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 4:09:32 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 4:09:32 PM] [Family Room TV] (Living Room TV)(Living Room TV)INFO - playPause option set to false
[4/5/2020, 4:09:32 PM] [Family Room TV] (Living Room TV)INFO - input names file does not exist
[4/5/2020, 4:09:32 PM] [Family Room TV] (Living Room TV)INFO - input visibility file does not exist
[4/5/2020, 4:09:32 PM] Loading 0 accessories...
Setup Payload:
X-HM://00250T3G5AJI7
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 938-50-293 │     
    └────────────┘     
                       
[4/5/2020, 4:09:32 PM] [DysonPureCoolPlatform] Cached accessories loaded.
[4/5/2020, 4:09:32 PM] [DysonPureCoolPlatform] Signing in.
[4/5/2020, 4:09:32 PM] [Family Room TV] DidFinishLaunching
[4/5/2020, 4:09:32 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 4:09:32 PM] [Family Room TV] INFO - Loading activities...
```
None Working
<img width="1010" alt="Screen Shot 2020-04-05 at 4 03 58 PM" src="https://user-images.githubusercontent.com/9875439/78510066-377d3000-7758-11ea-8ebb-c2d16e77663b.png">
![IMG_2610](https://user-images.githubusercontent.com/9875439/78510070-3ea43e00-7758-11ea-97ea-db72298fb9c7.jpg)

**Comment by donavanbecker** [comment]
Config for one Hub        
```
{
            "name": "Family Room TV",
            "hubName": "Family Room TV",
            "platform": "HarmonyHubWebSocket"
}
```
Log
```
[4/5/2020, 4:15:17 PM] [Family Room TV] Initializing HarmonyHubWebSocket platform...
[4/5/2020, 4:15:17 PM] [Family Room TV] HarmonyPlatform Init
[4/5/2020, 4:15:17 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 4:15:17 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 4:15:17 PM] [Family Room TV] (Family Room TV)(Family Room TV)INFO - playPause option set to false
[4/5/2020, 4:15:17 PM] [Family Room TV] (Family Room TV)INFO - input names file does not exist
[4/5/2020, 4:15:17 PM] [Family Room TV] (Family Room TV)INFO - input visibility file does not exist
[4/5/2020, 4:15:17 PM] Loading 0 accessories...
Setup Payload:
X-HM://00250T3G5AJI7
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 938-50-293 │     
    └────────────┘     
                       
[4/5/2020, 4:15:17 PM] [DysonPureCoolPlatform] Cached accessories loaded.
[4/5/2020, 4:15:17 PM] [DysonPureCoolPlatform] Signing in.
[4/5/2020, 4:15:17 PM] [Family Room TV] DidFinishLaunching
[4/5/2020, 4:15:17 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 4:15:17 PM] Homebridge is running on port 51910.
```
No Devices 
<img width="1010" alt="Screen Shot 2020-04-05 at 4 03 58 PM" src="https://user-images.githubusercontent.com/9875439/78510141-ba9e8600-7758-11ea-9a83-481154ed3fad.png">

**Comment by donavanbecker** [comment]
Config with IPs for 2 Hubs      
```
  {
            "name": "Family Room TV",
            "hubIP": "192.168.7.62",
            "otherPlatforms": [
                {
                    "name": "Living Room TV",
                    "hubName": "192.168.7.63"
                }
            ],
            "platform": "HarmonyHubWebSocket"
}
```
Log
```
[4/5/2020, 4:16:58 PM] [Family Room TV] Initializing HarmonyHubWebSocket platform...
[4/5/2020, 4:16:58 PM] [Family Room TV] HarmonyPlatform Init
[4/5/2020, 4:16:58 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 4:16:58 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 4:16:58 PM] [Family Room TV] (Family Room TV)(Family Room TV)INFO - playPause option set to false
[4/5/2020, 4:16:58 PM] [Family Room TV] (Family Room TV)INFO - input names file does not exist
[4/5/2020, 4:16:58 PM] [Family Room TV] (Family Room TV)INFO - input visibility file does not exist
[4/5/2020, 4:16:58 PM] [Family Room TV] INFO : following activites controls will be ignored if they are in the same state : NONE
[4/5/2020, 4:16:58 PM] [Family Room TV] INFO - remoteOverrideCommandsList is : undefined
[4/5/2020, 4:16:58 PM] [Family Room TV] (Living Room TV)(Living Room TV)INFO - playPause option set to false
[4/5/2020, 4:16:58 PM] [Family Room TV] (Living Room TV)INFO - input names file does not exist
[4/5/2020, 4:16:58 PM] [Family Room TV] (Living Room TV)INFO - input visibility file does not exist
[4/5/2020, 4:16:58 PM] Loading 0 accessories...
Setup Payload:
X-HM://00250T3G5AJI7
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 938-50-293 │     
    └────────────┘     
                       
[4/5/2020, 4:16:58 PM] [DysonPureCoolPlatform] Cached accessories loaded.
[4/5/2020, 4:16:58 PM] [DysonPureCoolPlatform] Signing in.
[4/5/2020, 4:16:58 PM] [Family Room TV] DidFinishLaunching
[4/5/2020, 4:16:58 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 4:16:58 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 4:16:58 PM] Homebridge is running on port 51910.
[4/5/2020, 4:17:00 PM] [DysonPureCoolPlatform] Signed in.
[4/5/2020, 4:17:01 PM] [DysonPureCoolPlatform] NM7-US-HHA3875A - MQTT connection requested for 192.168.7.71.
[4/5/2020, 4:17:01 PM] [DysonPureCoolPlatform] Got devices from the Dyson API.
[4/5/2020, 4:17:01 PM] [DysonPureCoolPlatform] NM7-US-HHA3875A - MQTT connection established.
[4/5/2020, 4:17:01 PM] [DysonPureCoolPlatform] NM7-US-HHA3875A - MQTT message received: {"msg":"CURRENT-STATE","time":"2020-04-05T21:17:00.000Z","mode-reason":"PRC","state-reason":"FLT","dial":"OFF","rssi":"-39","product-state":{"fmod":"OFF","fnst":"OFF","fnsp":"0005","qtar":"0004","oson":"OFF","rhtm":"ON","filf":"0243","ercd":"02C9","nmod":"OFF","wacd":"NONE"},"scheduler":{"srsc":"970f","dstv":"0001","tzid":"0001"}}
[4/5/2020, 4:17:01 PM] [DysonPureCoolPlatform] NM7-US-HHA3875A - MQTT message received: {"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","time":"2020-04-05T21:17:00.001Z","data":{"tact":"2934","hact":"0041","pact":"0000","vact":"0001","sltm":"OFF"}}
[4/5/2020, 4:17:09 PM] [Family Room TV] Error - Error retrieving info from hub : Error: ETIMEDOUT-(1)
[4/5/2020, 4:17:19 PM] [Family Room TV] INFO - Loading activities...
[4/5/2020, 4:17:29 PM] [Family Room TV] Error - Error retrieving info from hub : Error: ETIMEDOUT-(2)
[4/5/2020, 4:17:39 PM] [Family Room TV] INFO - Loading activities...
```

**Comment by nicoduj** [comment]
Thank you for all the tests, something is wrong , can I ask if you add cleaned your cache ? I don’t see any of my error logs must have missed something :(

What bothers me most is the fact that there is a timeout with ips , autodiscovery is not involved in that case ...

**Comment by donavanbecker** [comment]
@nicoduj I was using the homebridge@beta on this. Once I went back to 1.2.7 and homebridge@beta, it didn't work at all. went to homebridge@latest and the first TV worked and adding the second with ip worked. But doing it with names didn't

**Comment by nicoduj** [comment]
I am using also the beta for my tests . There is something there I don’t understand ... will check, thanks a lot  for your help .

By any chance do you have the same thing that is mentioned there : https://github.com/nicoduj/homebridge-harmony/issues/246

**Comment by donavanbecker** [comment]
> By any chance do you have the same thing that is mentioned there : #246
@nicoduj I do not.

**Comment by nicoduj** [comment]
Did you try to clean cached / persist folder between attemps ? Maybe something is wrong with this

**Comment by donavanbecker** [comment]
1. config of 2 hubs, without any option (no IP, no name for both) -> should log an error, no hub discovered
[config1.txt](https://github.com/nicoduj/homebridge-harmony/files/4439980/config1.txt)
[log1.txt](https://github.com/nicoduj/homebridge-harmony/files/4439981/log1.txt)

**Comment by donavanbecker** [comment]
2. config of 2 hubs, one with an IP, one without any option (no IP, no name) -> should log an error for second one, first should work.
[config2.txt](https://github.com/nicoduj/homebridge-harmony/files/4440005/config2.txt)
[log2.txt](https://github.com/nicoduj/homebridge-harmony/files/4440007/log2.txt)

**Comment by donavanbecker** [comment]
3. config of 2 hubs, one with a correct name, one without any option -> same as 2)
[config3.txt](https://github.com/nicoduj/homebridge-harmony/files/4440019/config3.txt)
[log3.txt](https://github.com/nicoduj/homebridge-harmony/files/4440020/log3.txt)

**Comment by donavanbecker** [comment]
4. config of 2 hubs, both with a name -> should work :)
[config4.txt](https://github.com/nicoduj/homebridge-harmony/files/4440027/config4.txt)
[log4.txt](https://github.com/nicoduj/homebridge-harmony/files/4440042/log4.txt)

**Comment by donavanbecker** [comment]
- [config of 2 hubs, without any option (no IP, no name for both) -> should log an error, no hub discovered](https://github.com/nicoduj/homebridge-harmony/files/4445442/1.txt)

- [config of 2 hubs, one with an IP, one without any option (no IP, no name) -> should log an error for second one, first should work](https://github.com/nicoduj/homebridge-harmony/files/4445472/2.txt)

- [config of 2 hubs, one with a correct name, one without any option -> same as 2](https://github.com/nicoduj/homebridge-harmony/files/4445494/3.txt)

- [config of 2 hubs, both with a name -> should work](https://github.com/nicoduj/homebridge-harmony/files/4445520/4.txt)

- [if you have some time, you can also try with a bad name for one hub.](https://github.com/nicoduj/homebridge-harmony/files/4445534/5.txt)

Links have attached txt files of config and log.
