### ISSUE TITLE
[BUG]UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by m4d-maNu** [nicoduj/homebridge-harmony#274]
Hi,
on my first Start comes this.

```
UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 8786b66e-b753-4fe7-8ce9-713ac4059b6f
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:414:15)
    at Bridge.Accessory._this.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:448:12)
    at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:527:17)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:316:10)
    at HarmonyBase.addAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:1236:25)
    at HarmonyBase.getDevicesAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:1132:12)
    at HarmonyBase.setupFoundAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:341:10)
    at HarmonySubPlatform.readAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:163:22)
    at /usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:93:27
(node:28760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When i stopp the homebridge an restart again comes this:
```
 Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 8786b66e-b753-4fe7-8ce9-713ac4059b6f
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:414:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

```

I hope someone can help me

**Comment by nicoduj** [comment]
Hi, can you share your config and version please ?

**Comment by m4d-maNu** [comment]
Of course 
Homebridge 1.1.0
Homebridge-harmony 1.3.1


and my config

```
{
	"bridge": {
		"name": "Harmony Hub",
		"username": "C4:22:3D:E3:CE:98",
		"port": "51898",
		"pin": "130-81-537"
	},
	"plugins": [
		"homebridge-harmony"
	],

	"accessories": [],

	"platforms": [{
		"platform": "HarmonyHubWebSocket",
		"name": "Ess- I Wohnzimmer Harmony",
		"hubIP": "192.168.1.24",
		"mainActivity": "Television",
		"publishGeneralVolumeSlider": true,
		"publishGeneralMuteSwitch": true,
		"showTurnOffActivity": true,
		"switchAccessories": true,
		"publishSwitchActivitiesAsIndividualAccessories": true,
		"addAllActivitiesToSkippedIfSameStateActivitiesList": true,
		"devicesToPublishAsAccessoriesSwitch": [
			"LED Candle Light RGB",
			"LED Candle Light RGB|6H;6H",
			"LED Candle Light RGB|Mode;Mode",
			"LED Candle Light RGB|RGB;RGB",
			"LED Candle Light RGB|White;White",
			"LED Candle Light RGB|Orange;Orange",
			"LED Candle Light RGB|Purple;Purple",
			"LED Candle Light RGB|Red;Red",
			"LED Candle Light RGB|Blue;Blue",
			"LED Candle Light RGB|Green;Green",
			"LED Candle Light RGB|Yellow;Yellow",
			"Telekom-DVR|ARD;Number1",
			"Telekom-DVR|ZDF;Number2",
			"Telekom-DVR|BR;Number3",
			"Telekom-DVR|Lokal TV;Number4",
			"Telekom-DVR|München TV;Number5",
			"Telekom-DVR|Servus TV;Numer6",
			"Telekom-DVR|RTL;Number7",
			"Telekom-DVR|RTL Nitro;Number8",
			"Telekom-DVR|RTL Plus;Number9",
			"Telekom-DVR|RTL 2;Number1;Number0",
			"Telekom-DVR|Super RTL;Number1;Number1",
			"Telekom-DVR|VOX;Number1;Number2",
			"Telekom-DVR|VOX Up;Number1;Number3",
			"Telekom-DVR|Comedy Central;Number1;Number4",
			"Telekom-DVR|Sat 1;Number1;Number5",
			"Telekom-DVR|Sat 1 Gold;Number1;Number6",
			"Telekom-DVR|Pro Sieben;Number1;Number7",
			"Telekom-DVR|Pro Sieben Maxx;Number1;Number8",
			"Telekom-DVR|SIXX;Number1;Number9",
			"Telekom-DVR|Kabel 1;Number2;Number0",
			"Telekom-DVR|ARD alpha;Number2;Number1",
			"Telekom-DVR|DMAX;Number2;Number2",
			"Telekom-DVR|Kabel 1 Doku;Number2;Number3",
			"Telekom-DVR|N 24 Doku;Number2;Number4",
			"Telekom-DVR|Welt der Wunder;Number2;Number5",
			"Telekom-DVR|ZDF info;Number2;NUmber6",
			"Telekom-DVR|Euro Sport 1;Number2;Number7",
			"Telekom-DVR|Sport 1;Number2;Number8",
			"Telekom-DVR|Sky Sport 1 News;Number2;Number9",
			"Telekom-DVR|Disney Channel;Number3;Number0",
			"Telekom-DVR|KiKa;Number3;Number1",
			"Telekom-DVR|Toggo Plus;Number3;Number2",
			"Telekom-DVR|Nick;Number3;Number3",
			"Telekom-DVR|MTV;Number3;Number4",
			"Telekom-DVR|Magenta Musik 1;Number3;Number5",
			"Telekom-DVR|Magenta Musik 2;Number3;Number6",
			"Telekom-DVR|Magenta Musik 3;Number3;Number7",
			"Telekom-DVR|Deluxe Musik;Number3;Number8",
			"Telekom-DVR|NTV;Number3;Number9",
			"Telekom-DVR|Phoenix;Number4;Number0",
			"Telekom-DVR|Tagesschau 24;Number4;Number1",
			"Telekom-DVR|Welt;Number4;Number2",
			"Telekom-DVR|3 Sat;Number4;Number3",
			"Telekom-DVR|ARTE;Number4;Number4",
			"Telekom-DVR|hr;Number4;Number5",
			"Telekom-DVR|MDR;Number4;Number6",
			"Telekom-DVR|NDR;Number4;Number7",
			"Telekom-DVR|one;Number4;Number8",
			"Telekom-DVR|rbb;Number4;Number9",
			"Telekom-DVR|SR;Number5;Number0",
			"Telekom-DVR|SWR;Number5;Number1",
			"Telekom-DVR|Tele 5;Number5;Number2",
			"Telekom-DVR|WDR;Number5;Number3",
			"Telekom-DVR|ZDF neo;Number5;Number4"
		],


		"otherPlatforms": [{
			"name": "Schlafzimmer Harmony",
			"hubIP": "192.168.1.25",
			"mainActivity": "Television",
			"publishGeneralVolumeSlider": true,
			"publishGeneralMuteSwitch": true,
			"showTurnOffActivity": true,
			"switchAccessories": true,
			"publishSwitchActivitiesAsIndividualAccessories": true,
			"addAllActivitiesToSkippedIfSameStateActivitiesList": true
		}]
	}]
}

```

**Comment by nicoduj** [comment]
wow,you did this config on the first attempt ? The error is because there is a duplicate deice in your conf I think (Same name) . You will have to clean your cached accessories (if you use latest Config UI you can do it in the UI), and maybe go step by step . Full log might help seeing which one is faulty

**Comment by m4d-maNu** [comment]
No, this config has grown. 

This is my older config and works:

```
{
	"bridge": {
		"name": "Harmony Hub",
		"username": "C4:22:3D:E3:CE:93",
		"port": "51893",
		"pin": "130-81-537"
	},
	"plugins": [
		"homebridge-harmony"
	],

	"accessories": [],

	"platforms": [{
		"platform": "HarmonyHubWebSocket",
		"name": "Ess- I Wohnzimmer Harmony",
		"hubIP": "192.168.1.24",
		"mainActivity": "Television",
		"publishGeneralVolumeSlider": true,
		"publishGeneralMuteSwitch": true,
		"showTurnOffActivity": true,
		"switchAccessories": true,
		"publishSwitchActivitiesAsIndividualAccessories": true,
		"addAllActivitiesToSkippedIfSameStateActivitiesList": true,
		"devicesToPublishAsAccessoriesSwitch": [
			"LED Candle Light RGB",
			"LED Candle Light RGB|6H;6H",
			"LED Candle Light RGB|Mode;Mode",
			"LED Candle Light RGB|RGB;RGB",
			"LED Candle Light RGB|White;White",
			"LED Candle Light RGB|Orange;Orange",
			"LED Candle Light RGB|Purple;Purple",
			"LED Candle Light RGB|Red;Red",
			"LED Candle Light RGB|Blue;Blue",
			"LED Candle Light RGB|Green;Green",
			"LED Candle Light RGB|Yellow;Yellow"
	
		],
		"otherPlatforms": [{
			"name": "Schlafzimmer Harmony",
			"hubIP": "192.168.1.25",
			"mainActivity": "Television",
			"publishGeneralVolumeSlider": true,
			"publishGeneralMuteSwitch": true,
			"showTurnOffActivity": true,
			"switchAccessories": true,
			"publishSwitchActivitiesAsIndividualAccessories": true,
			"addAllActivitiesToSkippedIfSameStateActivitiesList": true
		}]
	}]
}
```


okay, than I edit my config step by step with die Telekom-DVR Setting.

**Comment by nicoduj** [comment]
Moreover be aware that there is a limit I think per hub of number of devices (100), so might reach it :)

**Comment by m4d-maNu** [comment]
Thumps up.


Works now, the problem was in the Telekom-DVR Setting in the config. In a Line stand NUmber and not Number. In a other Line was an : and not an ;

It was to many text for my eyes ;)

**Comment by nicoduj** [comment]
To be honest , for me also :)
