### ISSUE TITLE
[BUG] No longer existing platform cannot be removed

### ISSUE THREAD

**Issue by pro-sumer** [nicoduj/homebridge-harmony#275]
**Describe the bug**
When I first started using this plugin (today) I used `"name": "HubName"` as is on your project page. I then discovered this will be used as the visible name in HomeKit, so I changed it to `"name": "Harmony"`.

Since then I see this in the logs:
```
May 28 22:27:01 pi-hb homebridge[4142]: [5/28/2020, 10:27:01 PM] [Harmony] WARNING - configureAccessory - The platform HubName is not there anymore in your config (name property). It won't be loaded and will be removed from cache.
May 28 22:27:01 pi-hb homebridge[4142]: [5/28/2020, 10:27:01 PM] [Harmony] WARNING - configureAccessory - The platform HubName could not be removed
```

**To Reproduce**

1. Use `"name": "HubName"` in your config
2. Restart Homebridge
3. Use `"name": "Harmony"` in your config 
4. Restart Homebridge

**Expected behavior**
* No warnings about the old platform (name)
* A single TV accessory, called "Harmony"

**Screenshots**
N/A

**iOS**
- 13.5 (17F75)
- iPhone X (A1901)

**Logs**
```
May 28 22:27:01 pi-hb homebridge[4142]: [5/28/2020, 10:27:01 PM] [Harmony] WARNING - configureAccessory - The platform HubName is not there anymore in your config (name property). It won't be loaded and will be removed from cache.
May 28 22:27:01 pi-hb homebridge[4142]: [5/28/2020, 10:27:01 PM] [Harmony] WARNING - configureAccessory - The platform HubName could not be removed
May 28 22:27:01 pi-hb homebridge[4142]: [5/28/2020, 10:27:01 PM] [Harmony] DidFinishLaunching
May 28 22:27:01 pi-hb homebridge[4142]: [5/28/2020, 10:27:01 PM] [Harmony] (Harmony)INFO - Loading activities...
```

and

```
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)INFO - Adding Accessory : Harmony-TV
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)INFO - configuring Main TV Service
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)INFO - Creating TV Service
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)INFO - Creating Input Service - Radio
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)INFO - Creating Input Service - TV
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)INFO - Creating Input Service - Music
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)INFO - Creating Input Service - Movie
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)INFO - Configuring Main Activity Apple TV
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)INFO - Creating TV Speaker Service
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)INFO - Creating Input Service - Apple TV
May 28 22:27:03 pi-hb homebridge[4142]: [5/28/2020, 10:27:03 PM] [Harmony] (Harmony)WARNING - setupFoundAccessories - TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
```

**Config**
```
	{
		"platform": "HarmonyHubWebSocket",
		"name": "Harmony",
		"hubName": "Harmony Hub",
		"hubIP": "192.168.1.214",
		"mainActivity": "Apple TV",
		"linkVolumeControlToTV": "true"
	}
```

**Additional context**

There are two TV accessories in the Home App now, "HubName" and "Harmony". Adding `"cleanCache": true` to the config and restarting Homebridge did not help to get rid of "HubName".

Worse, there's only one remote control "HubName" (none for "Harmony"), so I can't use the remote control in Control Center (my goal is to change the volume of my amplifier using the physical volume buttons; this works in the Harmony App for the "Apple TV" activity).

I hope we can solve this without removing the bridge from HomeKit as there are several other accessories defined in Homebridge that are heavily used in automations. If I have to remove the bridge I have to manually fix all those automations...

**Comment by nicoduj** [comment]
Hi, I can reproduce. However, There is a problem I think with homebridge there, will try to check with them. When I try to remove the accessory that is loaded from cache, homebridge throw an error (That I catch).
You could still remove it manually from your cache accessory file I think, or through configUI (but since you are using hoobs, ou won't have this option).

Here is what I got when I remove the try / catch :

Code involved : 

```javascript
 configureAccessory: function (accessory) {
    let platformName = accessory.context.subPlatformName;
    var platform;

    if (this.platforms && this.platforms.length > 0)
      platform = this.platforms.find((x) => x.name == platformName);

    if (platform == undefined) {
      this.log(
        'WARNING - configureAccessory - The platform ' +
          platformName +
          " is not there anymore in your config (name property). It won't be loaded and will be removed from cache."
      );
        this.log(accessory);
     // try {
        this.api.unregisterPlatformAccessories(
          'homebridge-harmony',
          'HarmonyHubWebSocket',
          [
            accessory,
          ]
        );
      // } catch {
      //   this.log(
      //     'WARNING - configureAccessory - The platform ' + platformName + ' could not be removed'
      //   );
      // }
    } else {
      this.log.debug(
        accessory.displayName,
        'Got cached Accessory ' + accessory.UUID + ' for ' + platform.name
      );

      platform._foundAccessories.push(accessory);

      if (accessory.category == AccessoryType.TELEVISION) {
        this._oneTVAdded = true;
        this.log(
          'WARNING - configureAccessory - TV accessory added in your bridge from cache, if another plugin is exposing a TV accessory this one might not be visible in your remote widget'
        );
      }
    }
  },
```

Logs : 

```bash
[2020-5-29 7:44:36] [DEV TEST 2] PlatformAccessory {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  services: [
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: '',
      UUID: '0000003E-0000-1000-8000-0026BB765291',
      subtype: undefined,
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    },
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: 'DEV TEST 1',
      UUID: '000000D8-0000-1000-8000-0026BB765291',
      subtype: 'DEV TEST 1 TV',
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [Array],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    },
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: 'DEV TEST 1',
      UUID: '000000D9-0000-1000-8000-0026BB765291',
      subtype: 'Vinyl Activity',
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    },
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: 'DEV TEST 1',
      UUID: '000000D9-0000-1000-8000-0026BB765291',
      subtype: 'La PS4 Activity',
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    },
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: 'DEV TEST 1',
      UUID: '000000D9-0000-1000-8000-0026BB765291',
      subtype: 'La Switch Activity',
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    },
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: 'DEV TEST 1',
      UUID: '000000D9-0000-1000-8000-0026BB765291',
      subtype: 'La TV Activity',
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    },
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: 'DEV TEST 1',
      UUID: '000000D9-0000-1000-8000-0026BB765291',
      subtype: 'Un Film Activity',
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    },
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: 'DEV TEST 1',
      UUID: '000000D9-0000-1000-8000-0026BB765291',
      subtype: 'La musique Activity',
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    },
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: 'DEV TEST 1',
      UUID: '00000113-0000-1000-8000-0026BB765291',
      subtype: 'DEV TEST 1 Volume',
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    },
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: 'DEV TEST 1',
      UUID: '000000DA-0000-1000-8000-0026BB765291',
      subtype: 'DEV TEST 1 AccessControlService',
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    },
    Service {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      displayName: 'DEV TEST 1',
      UUID: '00000228-0000-1000-8000-0026BB765291',
      subtype: 'DEV TEST 1 SmartSpeaker',
      iid: null,
      name: null,
      characteristics: [Array],
      optionalCharacteristics: [Array],
      isHiddenService: false,
      isPrimaryService: false,
      linkedServices: [],
      addCharacteristic: [Function],
      setPrimaryService: [Function],
      setHiddenService: [Function],
      addLinkedService: [Function],
      removeLinkedService: [Function],
      removeCharacteristic: [Function],
      testCharacteristic: [Function],
      setCharacteristic: [Function],
      updateCharacteristic: [Function],
      addOptionalCharacteristic: [Function],
      getCharacteristicByIID: [Function],
      _assignIDs: [Function],
      toHAP: [Function],
      _setupCharacteristic: [Function],
      _sideloadCharacteristics: [Function],
      [Symbol(kCapture)]: false
    }
  ],
  reachable: false,
  context: { subPlatformName: 'DEV TEST 1' },
  _associatedHAPAccessory: Accessory {
    _events: [Object: null prototype] { identify: [Function] },
    _eventsCount: 1,
    _maxListeners: undefined,
    displayName: 'DEV TEST 1-TV',
    UUID: 'c9f2bbaa-7a89-49cc-940b-d5b04462f586',
    aid: null,
    _isBridge: false,
    bridged: false,
    bridgedAccessories: [],
    reachable: true,
    category: 1,
    services: [
      [Service], [Service],
      [Service], [Service],
      [Service], [Service],
      [Service], [Service],
      [Service], [Service],
      [Service]
    ],
    shouldPurgeUnusedIDs: true,
    controllers: {},
    _setupID: null,
    controllerStorage: ControllerStorage {
      initialized: false,
      fileCreated: false,
      purgeUnidentifiedAccessoryData: true,
      trackedControllers: [],
      controllerData: {},
      accessoryUUID: 'c9f2bbaa-7a89-49cc-940b-d5b04462f586'
    },
    _identificationRequest: [Function],
    addService: [Function],
    setPrimaryService: [Function],
    removeService: [Function],
    getService: [Function],
    getPrimaryAccessory: [Function],
    updateReachability: [Function],
    addBridgedAccessory: [Function],
    addBridgedAccessories: [Function],
    removeBridgedAccessory: [Function],
    removeBridgedAccessories: [Function],
    removeAllBridgedAccessories: [Function],
    getCharacteristicByIID: [Function],
    getBridgedAccessoryByAID: [Function],
    findCharacteristic: [Function],
    setupURI: [Function],
    _assignIDs: [Function],
    disableUnusedIDPurge: [Function],
    enableUnusedIDPurge: [Function],
    purgeUnusedIDs: [Function],
    toHAP: [Function],
    publish: [Function],
    destroy: [Function],
    unpublish: [Function],
    _updateConfiguration: [Function],
    _onListening: [Function],
    _handleIdentify: [Function],
    _handlePair: [Function],
    _handleAddPairing: [Function],
    _handleRemovePairing: [Function],
    _handleListPairings: [Function],
    _handleAccessories: [Function],
    _handleGetCharacteristics: [Function],
    _handleSetCharacteristics: [Function],
    _handleSessionClose: [Function],
    _unsubscribeEvents: [Function],
    _handleCharacteristicChange: [Function],
    _setupService: [Function],
    _sideloadServices: [Function],
    _generateSetupID: [Function],
    lastKnownUsername: undefined,
    [Symbol(kCapture)]: false
  },
  displayName: 'DEV TEST 1-TV',
  UUID: 'c9f2bbaa-7a89-49cc-940b-d5b04462f586',
  category: 1,
  _associatedPlugin: 'homebridge-harmony',
  _associatedPlatform: 'HarmonyHubWebSocket',
  [Symbol(kCapture)]: false
}
[2020-5-29 7:44:36] Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory._this.removeBridgedAccessory (/Users/nicolas/Documents/GitHub/homebridgeBeta/node_modules/hap-nodejs/src/lib/Accessory.ts:470:13)
    at Bridge.Accessory._this.removeBridgedAccessories (/Users/nicolas/Documents/GitHub/homebridgeBeta/node_modules/hap-nodejs/src/lib/Accessory.ts:482:12)
    at Server.handleUnregisterPlatformAccessories (/Users/nicolas/Documents/GitHub/homebridgeBeta/src/server.ts:500:17)
    at HomebridgeAPI.emit (events.js:311:20)
    at HomebridgeAPI.unregisterPlatformAccessories (/Users/nicolas/Documents/GitHub/homebridgeBeta/src/api.ts:311:10)
    at HarmonyPlatform.configureAccessory (/Users/nicolas/Documents/GitHub/HomebridgePlugins/homebridge-harmony/harmonyPlatform.js:117:18)
    at /Users/nicolas/Documents/GitHub/homebridgeBeta/src/server.ts:284:28
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/Users/nicolas/Documents/GitHub/homebridgeBeta/src/server.ts:268:69)
    at Server.start (/Users/nicolas/Documents/GitHub/homebridgeBeta/src/server.ts:156:10)
    at cli (/Users/nicolas/Documents/GitHub/homebridgeBeta/src/cli.ts:74:10)
    at Object.<anonymous> (/Users/nicolas/Documents/GitHub/homebridgeBeta/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by pro-sumer** [comment]
I’m not (aware of) using Hoobs...

What indicates that I do?

(Trying to learn)

**Comment by nicoduj** [comment]
sorry, a confusion by my side.

**Comment by pro-sumer** [comment]
No worries.

How do I manually remove an accessory?

Or in the GUI?

(I would like to prevent removing my other accessories, so not removing entire folders)

**Comment by nicoduj** [comment]
in Homebridge Settings (top rgiht ) of config UI -X - Remove Single Cached Accessory

<img width="1393" alt="Capture d’écran 2020-05-29 à 17 49 31" src="https://user-images.githubusercontent.com/19813688/83279076-d4969b00-a1d4-11ea-8391-b84712fe0858.png">

**Comment by nicoduj** [comment]
check 1.3.11 should solve the issue

**Comment by pro-sumer** [comment]
Yes, 1.3.11 does solve my issue:

I now have only one Harmony remote in the control center and can control the volume of my amplifier using the physical buttons of my iPhone. Awesome!

Thank you!
