### ISSUE TITLE
Error after updating in Hoobs

### ISSUE THREAD

**Issue by McDin** [nicoduj/homebridge-harmony#277]
Hi,

I get following error after updating in Hoobs. I allready tried to install it manually or to use older versions but I always get following error, when I start the services:

[Homebridge] [6/2/2020, 1:23:35 PM] Error: The requested platform 'HarmonyHubWebSocket' was not registered by any plugin.
    at API.platform (/hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
    at Server._loadPlatforms (/hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
    at Server.run (/hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

Can you please help?

Thanks

**Comment by nicoduj** [comment]
Hi, it seems to be hoobs related could you check with their support first ?
