### ISSUE TITLE
[BUG] Homebridge service stops when Harmony Hub disconnects from network

### ISSUE THREAD

**Issue by mwhaley99** [nicoduj/homebridge-harmony#281]
**Describe the bug**
Homebridge service on HOOBS device stops when Harmony Hub disconnects from network.
e.g. cut power to device or reboots

**To Reproduce**
cut power to device and plug back immediately

**Expected behavior**
I would expect the device to show not responding until it talks back with Hoobs after it reconnects.

**Logs**
6/10/2020, 8:58:37 AM [Harmony Office] (Harmony Office)WARNING - socket closed
6/10/2020, 8:58:47 AM [Harmony Office] INFO - starting hub discovery
6/10/2020, 8:58:48 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:902:11)
    at Socket.send (dgram.js:627:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
6/10/2020, 8:58:48 AM Got SIGTERM, shutting down Bridge...
6/10/2020, 8:58:48 AM [Harmony Office] INFO - shutdown
6/10/2020, 8:58:49 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:902:11)
    at Socket.send (dgram.js:627:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
6/10/2020, 8:58:50 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:902:11)
    at Socket.send (dgram.js:627:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
6/10/2020, 8:58:51 AM Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:902:11)
    at Socket.send (dgram.js:627:3)
    at Ping.emit (/home/hoobs/.hoobs/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Config**
{
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "Harmony Office",
            "hubName": "Harmony Office",
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": true,
            "switchAccessories": true,
            "otherPlatforms": [
                {
                    "name": "Harmony LV",
                    "hubName": "Harmony LV",
                    "cleanCache": false,
                    "publishAllTVAsExternalAccessory": true,
                    "switchAccessories": true
                },
                {
                    "name": "Harmony GB",
                    "hubName": "Harmony GB",
                    "cleanCache": false,
                    "publishAllTVAsExternalAccessory": true,
                    "switchAccessories": true
                }
            ],
            "activitiesToPublishAsInputForTVMode": [],
            "remoteOverrideCommandsList": [],
            "activitiesToPublishAsAccessoriesSwitch": [],
            "skippedIfSameStateActivities": [],
            "devicesToPublishAsAccessoriesSwitch": [],
            "sequencesToPublishAsAccessoriesSwitch": [],
            "homeControlsToPublishAsAccessoriesSwitch": []
        }

**Comment by nicoduj** [comment]
Thanks for reporting. It is a socket issues on the underlying lib, can't do much about it. It is however strange since I have no such issue when I do such things, If you go on IP (fixed) config might be more reliable I think.
