### ISSUE TITLE
Disconnected Harmony causes error on restart

### ISSUE THREAD

**Issue by colethorsen** [nicoduj/homebridge-harmony#285]
**Describe the bug**
When the Harmony Hub goes down and loses its network connection, it takes down the entire homebridge setup, as homebridge is unable to start due to an undefined variable.

**To Reproduce**
Disconnect Harmony Hub from network, reboot homebridge.

**Expected behavior**
The application shouldn't take down the entire homebridge boot, if it can't find the Harmony Hub.

**IOS (please complete the following information):**
- Version 13.5.1
- Device: iPhone X

**Logs**
TypeError: Cannot read property 'length' of undefined
    at HarmonyBase.checkHubsFound (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:126:24)
    at HarmonyPlatform.harmonyPlatform.mainPlatform.on (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:227:16)
    at HarmonyPlatform.emit (events.js:197:13)
    at Timeout.setTimeout (/usr/local/lib/node_modules/homebridge-harmony/harmonyPlatform.js:168:16)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)

**Config**
{
            "name": "Living Room",
            "hubName": "Living Room",
            "TVAccessory": true,
            "mainActivity": "Watch TV",
            "showCommandsAtStartup": true,
            "platform": "HarmonyHubWebSocket"
        }

**Additional context**

**Comment by nicoduj** [comment]
#300 seems to be the same. Closing to have only one issue
