### ISSUE TITLE
Harmony offline from Wifi - homebridge crashes

### ISSUE THREAD

**Issue by homeconnector** [nicoduj/homebridge-harmony#300]
**Describe the bug**
Harmony was offline, however, the entire homebridge crashed upon start up - see logs

**To Reproduce**
Disconnect Harmony Hub from Wifi

**Expected behavior**
Error handling would have detected this, but allowed the rest of the homebridge to proceed

**Screenshots**
See Logs above

**IOS (please complete the following information):**
IOS 14

**Logs**
[9/19/2020, 4:51:05 PM] TypeError: Cannot read property 'length' of undefined
    at HarmonyBase.checkHubsFound (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:126:24)
    at HarmonyPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:227:16)
    at HarmonyPlatform.emit (events.js:315:20)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-harmony/harmonyPlatform.js:168:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Config**
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Bridge"
        },

**Additional context**
Can you modify the exception handling so it doesn't cause a complete crash of the homebridge

**Comment by nicoduj** [comment]
Hi, thanks for reporting . Can you share your config please (autodiscovery mode especially)

**Comment by homeconnector** [comment]
how do i enable the autodiscovery mode?  what setting? or is there a special harmony file?

i changed the wifi password, so the harmony wasn't connecting.   when restarting up the homebridge - it was crashing.

**Comment by homeconnector** [comment]
this is the only setting i have for harmony

Config
{
"platform": "HarmonyHubWebSocket",
"name": "Bridge"
},

**Comment by homeconnector** [comment]
**_Note - i was recently having this issue - after fixing the wifi password on the harmony, but was having stability issues.  **
[9/22/2020, 5:10:41 AM] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:888:11)
    at Socket.send (dgram.js:613:3)
    at Ping.emit (/usr/local/lib/node_modules/homebridge-harmony/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)


After upgrading to homebridge 1.2.3, and homebridge-harmony@1.3.12 - homekit seems more stable.   will monitor.

**Comment by homeconnector** [comment]
Seems to be constantly crashing with IOS 14.2, Homebridge 1.2.3 and homebridge-harmony@1.3.12.   I've removed the HarmonyWebSocket configuration and it is working ok

**Comment by nicoduj** [comment]
Hi,

sorry for my late answer.

Can you try with fixed ip ? When you say constantly crash, what do you mean ?
