### ISSUE TITLE
[Potential Bug with Homebridge Beta 1.3.0]  - Don't use activity id as identifier for input source since it only allow UINT32

### ISSUE THREAD

**Issue by dVIAN13** [nicoduj/homebridge-harmony#315]
Hello,

I am not sure if this can be addressed or not, however, on the latest version of Homebridge beta, I receive the following 'warning' a lot during startup.

`Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.`

Installation Details:
homebridge-harmony(v1.4.0)
home bridge(1.3.0beta14)
hap-nodejs(0.9.0-beta.43)

Full Log:
```[10/29/2020, 8:35:59 AM] [Living Room] (Media Room)INFO - Adding Accessory : Media Room-TV
[10/29/2020, 8:35:59 AM] [Living Room] (Media Room)INFO - configuring Main TV Service
[10/29/2020, 8:35:59 AM] [Living Room] (Media Room)INFO - Creating TV Service
[10/29/2020, 8:35:59 AM] [Living Room] (Media Room)INFO - Creating Input Service - Apple TV
[10/29/2020, 8:35:59 AM] [Living Room] (Media Room)INFO - Configuring Main Activity Tivo
[10/29/2020, 8:35:59 AM] [Living Room] (Media Room)INFO - Creating TV Speaker Service
[10/29/2020, 8:35:59 AM] [Living Room] (Media Room)INFO - Creating Input Service - Tivo
[10/29/2020, 8:35:59 AM] [Living Room] (Media Room)INFO - setupFoundAccessories - TV accessory added as external accessory
2020-10-29T15:35:59.120Z ciao:Responder [Media Room-TV 1A60._hap._tcp.local.] Going to advertise service...
[10/29/2020, 8:35:59 AM] Media Room-TV 1A60 is running on port 43819.
[10/29/2020, 8:35:59 AM] Please add [Media Room-TV 1A60] manually in Home app. Setup Code: XX-XX-XXX
2020-10-29T15:35:59.217Z ciao:Prober Probing for 'Homebridge 43C2 4BC8._hap._tcp.local.' finished successfully
2020-10-29T15:35:59.217Z ciao:Announcer [Homebridge 43C2 4BC8._hap._tcp.local.] Sending announcement for service
2020-10-29T15:35:59.217Z ciao:CiaoService [Homebridge 43C2 4BC8] Rebuilding service records...
2020-10-29T15:35:59.218Z ciao:CiaoService [Media Room-TV 1A60] Rebuilding service records...
2020-10-29T15:35:59.218Z ciao:Prober Starting to probe for 'Media Room-TV 1A60._hap._tcp.local.'...
2020-10-29T15:35:59.322Z ciao:Prober Sending prober query number 1 for 'Media Room-TV 1A60._hap._tcp.local.'...
[10/29/2020, 8:35:59 AM] [Living Room] (Living Room)INFO - Adding Accessory : Living Room-TV
[10/29/2020, 8:35:59 AM] [Living Room] (Living Room)INFO - configuring Main TV Service
[10/29/2020, 8:35:59 AM] [Living Room] (Living Room)INFO - Creating TV Service
[10/29/2020, 8:35:59 AM] [Living Room] (Living Room)INFO - Creating Input Service - Xbox
[10/29/2020, 8:35:59 AM] [Living Room] (Living Room)INFO - Configuring Main Activity Tivo
[10/29/2020, 8:35:59 AM] [Living Room] (Living Room)INFO - Creating TV Speaker Service
[10/29/2020, 8:35:59 AM] [Living Room] (Living Room)INFO - Creating Input Service - Tivo
[10/29/2020, 8:35:59 AM] [Living Room] (Living Room)INFO - Creating Input Service - Apple TV
[10/29/2020, 8:35:59 AM] [Living Room] (Living Room)INFO - setupFoundAccessories - TV accessory added as external accessory
2020-10-29T15:35:59.346Z ciao:Responder [Living Room-TV BAF8._hap._tcp.local.] Going to advertise service...
[10/29/2020, 8:35:59 AM] Living Room-TV BAF8 is running on port 34481.
[10/29/2020, 8:35:59 AM] Please add [Living Room-TV BAF8] manually in Home app. Setup Code: XXX-XX-XX
2020-10-29T15:35:59.493Z ciao:Prober 'Media Room-TV 1A60._hap._tcp.local.' won the tiebreak. We gonna ignore the other probing request!
2020-10-29T15:35:59.573Z ciao:Prober Sending prober query number 2 for 'Media Room-TV 1A60._hap._tcp.local.'...
2020-10-29T15:35:59.824Z ciao:Prober Sending prober query number 3 for 'Media Room-TV 1A60._hap._tcp.local.'...
2020-10-29T15:36:00.076Z ciao:Prober Probing for 'Media Room-TV 1A60._hap._tcp.local.' finished successfully
2020-10-29T15:36:00.076Z ciao:Announcer [Media Room-TV 1A60._hap._tcp.local.] Sending announcement for service
2020-10-29T15:36:00.077Z ciao:CiaoService [Media Room-TV 1A60] Rebuilding service records...
2020-10-29T15:36:00.077Z ciao:CiaoService [Living Room-TV BAF8] Rebuilding service records...
2020-10-29T15:36:00.077Z ciao:Prober Starting to probe for 'Living Room-TV BAF8._hap._tcp.local.'...
2020-10-29T15:36:00.078Z ciao:Announcer [Media Room-TV 1A60._hap._tcp.local.] Sending announcement number 1
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
2020-10-29T15:36:00.222Z ciao:Announcer [Homebridge 43C2 4BC8._hap._tcp.local.] Sending announcement number 2
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
2020-10-29T15:36:00.309Z ciao:Prober Sending prober query number 1 for 'Living Room-TV BAF8._hap._tcp.local.'...
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
2020-10-29T15:36:00.560Z ciao:Prober Sending prober query number 2 for 'Living Room-TV BAF8._hap._tcp.local.'...
[10/29/2020, 8:36:00 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
2020-10-29T15:36:00.812Z ciao:Prober Sending prober query number 3 for 'Living Room-TV BAF8._hap._tcp.local.'...
2020-10-29T15:36:01.063Z ciao:Prober Probing for 'Living Room-TV BAF8._hap._tcp.local.' finished successfully
2020-10-29T15:36:01.063Z ciao:Announcer [Living Room-TV BAF8._hap._tcp.local.] Sending announcement for service
2020-10-29T15:36:01.063Z ciao:CiaoService [Living Room-TV BAF8] Rebuilding service records...
2020-10-29T15:36:01.065Z ciao:Announcer [Living Room-TV BAF8._hap._tcp.local.] Sending announcement number 1
2020-10-29T15:36:01.080Z ciao:Announcer [Media Room-TV 1A60._hap._tcp.local.] Sending announcement number 2
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[10/29/2020, 8:36:01 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
2020-10-29T15:36:02.067Z ciao:Announcer [Living Room-TV BAF8._hap._tcp.local.] Sending announcement number 2```

**Comment by dVIAN13** [comment]
Thanks @nicoduj . FYI, after update, I still receive the error/warning:

```[11/11/2020, 7:09:49 AM] [Living Room] (Media Room)INFO - Adding Accessory : Media Room-TV
[11/11/2020, 7:09:49 AM] [Living Room] (Media Room)INFO - configuring Main TV Service
[11/11/2020, 7:09:49 AM] [Living Room] (Media Room)INFO - Creating TV Service
[11/11/2020, 7:09:49 AM] [Living Room] (Media Room)INFO - Creating Input Service - Apple TV
[Identifier@Media Room-TV] characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:09:49 AM] [Living Room] (Media Room)INFO - Configuring Main Activity Tivo
[11/11/2020, 7:09:49 AM] [Living Room] (Media Room)INFO - Creating TV Speaker Service
[11/11/2020, 7:09:49 AM] [Living Room] (Media Room)INFO - Creating Input Service - Tivo
[Identifier@Media Room-TV] characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:09:49 AM] [Living Room] (Media Room)INFO - setupFoundAccessories - TV accessory added as external accessory
2020-11-11T15:09:49.262Z ciao:Responder [Media Room-TV 1A60._hap._tcp.local.] Going to advertise service...
[11/11/2020, 7:09:49 AM] Media Room-TV 1A60 is running on port 42531.
[11/11/2020, 7:09:49 AM] Please add [Media Room-TV 1A60] manually in Home app. Setup Code: XXX-XX-XXX
2020-11-11T15:09:49.263Z ciao:CiaoService [Media Room-TV 1A60] Rebuilding service records...
2020-11-11T15:09:49.263Z ciao:Prober Starting to probe for 'Media Room-TV 1A60._hap._tcp.local.'...
2020-11-11T15:09:49.323Z ciao:Prober Sending prober query number 1 for 'Media Room-TV 1A60._hap._tcp.local.'...
2020-11-11T15:09:49.574Z ciao:Prober Sending prober query number 2 for 'Media Room-TV 1A60._hap._tcp.local.'...
2020-11-11T15:09:49.825Z ciao:Prober Sending prober query number 3 for 'Media Room-TV 1A60._hap._tcp.local.'...
2020-11-11T15:09:49.843Z ciao:Announcer [Homebridge 43C2 4BC8._hap._tcp.local.] Sending announcement number 2
2020-11-11T15:09:50.076Z ciao:Prober Probing for 'Media Room-TV 1A60._hap._tcp.local.' finished successfully
2020-11-11T15:09:50.076Z ciao:Announcer [Media Room-TV 1A60._hap._tcp.local.] Sending announcement for service
2020-11-11T15:09:50.076Z ciao:CiaoService [Media Room-TV 1A60] Rebuilding service records...
2020-11-11T15:09:50.077Z ciao:Announcer [Media Room-TV 1A60._hap._tcp.local.] Sending announcement number 1
[11/11/2020, 7:09:50 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[11/11/2020, 7:09:50 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[11/11/2020, 7:09:50 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[11/11/2020, 7:09:50 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[11/11/2020, 7:09:50 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[11/11/2020, 7:09:50 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[11/11/2020, 7:09:50 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[11/11/2020, 7:09:50 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[11/11/2020, 7:09:50 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
2020-11-11T15:09:51.081Z ciao:Announcer [Media Room-TV 1A60._hap._tcp.local.] Sending announcement number 2
[11/11/2020, 7:09:51 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[11/11/2020, 7:13:53 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:13:53 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:13:53 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:13:53 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:13:53 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:13:53 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:13:53 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:13:53 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:13:53 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!
[11/11/2020, 7:13:53 AM] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.```

Please let me know if I can provide any additional information. Thank you!

**Comment by nicoduj** [comment]
thank you, will have to test with homebridge beta so, since I removed the -1 I was setting explicitely but seems to have other problems.

**Comment by nicoduj** [comment]
Need to store a map betwwen activityids and input source identifiers as Uint32 (or do some hash magic)

**Comment by dVIAN13** [comment]
Thank you for continuing to look into this @nicoduj. Is this something you can/are willing to implement? Noticed it went to closed. Thanks, again!

**Comment by vcdx71** [comment]
I'm seeing this is beta 53

08/02/2021, 15:02:55] The plugin 'homebridge-harmony' slows down requests made to homebridge! The read handler for the characteristic 'Active' was slow to respond!
[08/02/2021, 15:03:02] The plugin 'homebridge-harmony' slows down requests made to homebridge! The read handler for the characteristic 'Active' didn't respond at all!. Please check that you properly call the callback!
[08/02/2021, 15:03:46] [Theater Harmony] (Theater Harmony)ERROR (1)- refreshCurrentActivity Error: WebSocket closed with reason: Socket Error: read ECONNRESET (1006). - Stack : Error: WebSocket closed with reason: Socket Error: read ECONNRESET (1006).
    at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:351:19)
    at W3CWebSocket.listener (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:309:63)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/local/lib/node_modules/homebridge-harmony/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.handleSocketClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:673:12)
[08/02/2021, 15:03:46] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active': characteristic was supplied illegal value: undefined! This might throw errors in the future!
[08/02/2021, 15:03:46] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: undefined! This might throw errors in the future!
[08/02/2021, 15:03:46] [Theater Harmony] (Theater Harmony)WARNING - socket closed
[08/02/2021, 15:03:46] [Theater Harmony] (Theater Harmony)WARNING - socket closed
[08/02/2021, 15:03:56] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.
[08/02/2021, 15:04:51] Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0.

**Comment by genfersee** [comment]
Yes, same errors for me with 1.3.0beta47.

**Comment by knedd** [comment]
Now that Homebridge 1.3.0 is public, will this warning be addressed soon in a updated release? The error messages are quite frequent. 

Thanks.

**Comment by nicoduj** [comment]
Working on it, still need to do more tests ...
