### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by sddgit** [nicoduj/homebridge-harmony#329]
Forgive me - newbie here. If there's a better place to discuss these issues, please let me know!

I am interested to know how people use this plugin. For me, I think the most exciting use would be using Siri to turn on a TV, switch inputs, adjust volume, mute etc. I'm struggling to figure out the best way to do this. Publishing as a TV accessory gives you the nice TV button in a room in the Home app, and you can change inputs from there. But I can't find a way to control that using Siri, other than maybe using Shortcuts. And with 5 Harmony hubs, I'd end up with an awful lot of shortcuts! If I publish activities as accessories, I can use Siri to turn on an accessory, which switches as appropriate. But then to turn off I have to say to switch off the current accessory - I can't just say to turn the TV off. Then there is the question of how to control volume and mute. Id also like to be able to tell Siri to change channels.

As I said, I'd love to discuss how people have gone about setting up this plugin, given the number of ways to set it up. Thank you.

**Comment by nicoduj** [comment]
You can publish both switches and the tv accessory. With correct naming, you will be able to turn off its Siri and hangs inputs through switches . Unfortunately Siri does not understand inputs as far as I know of the tv accessory

**Comment by sddgit** [comment]
Thank you for the quick reply! Ah yes, if I publish both I could turn the TV accessory on/off easily using Siri, and switch inputs using the switches. Is there a way to set the default activity when I use the TV accessory? Any thoughts on volume control/mute/channel changing?

I also keep reading about some sort of remote app/screen on an iPhone that could control activities. For example "Buttons on the remote app and volume controls will be binded to the one defined in the activity (if so). VOLUME IS BIND TO PHYSICAL BUTTONS WHEN REMOTE FROM CONTROL CENTER IS SHOWN . There is an option to override default mappings." What is this exactly?

**Comment by nicoduj** [comment]
You have an option called mainActivity for the default activity on tv accessory.

Controls are available through remote control widgets on your phone (in control center) while the widget is open, you can use volume up / down (never found mute even if it is exposed in HomeKit)

**Comment by sddgit** [comment]
Thank you very much. I presume you mean the “Apple TV” remote control app in Control Centre? I just realised that when you use that you can then change the TV being controlled. I have so many Apple TV’s that the Harmony ones were scrolled off the bottom of the list. Apologies, I should have seen the mainActivity option. I will now play with all this and see how I go. I’m thinking I could use some Harmony sequencies to expose channel changes, and maybe volume switches (rather than a slider) to enable Siri control of volume.

Meanwhile, I’ve seen some crashes. Log:

12/23/2020, 8:56:09 AM] [Lounge] (Master Bedroom)WARNING - socket closed
[12/23/2020, 8:56:19 AM] [Lounge] INFO - starting hub discovery
[12/23/2020, 8:56:20 AM] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/23/2020, 8:56:20 AM] Got SIGTERM, shutting down Homebridge...
[12/23/2020, 8:56:20 AM] [Lounge] INFO - shutdown
[12/23/2020, 8:56:21 AM] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/23/2020, 8:56:22 AM] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/23/2020, 8:56:24 AM] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/23/2020, 8:56:25 AM] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.send (dgram.js:622:3)
    at Ping.emit (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/node_modules/harmonyhubjs-discover/lib/ping.js:25:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/23/2020, 8:56:25 AM] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:897:11)
    at Socket.close (dgram.js:719:3)
    at Ping.stop (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/node_modules/harmonyhubjs-discover/lib/ping.js:43:15)
    at Explorer.stop (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/node_modules/harmonyhubjs-discover/lib/explorer.js:81:13)
    at Timeout._onTimeout (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/harmonyPlatform.js:165:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/23/2020, 8:56:25 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/23/2020, 8:56:30 AM] [HB Supervisor] Restarting Homebridge...

**Comment by nicoduj** [comment]
Hi, the error is network related, what version of homebridge are you running / in what environment ? I saw same error in homebridge itself with new CIAO lib .... And since you have a lot of hubs maybe it is related.

**Comment by sddgit** [comment]
I'm running V1.1.7 on a Mac, with Node V14.15.3. I uninstalled this plugin a few days ago, and haven't seen any errors since, but am about to re-install it to try again. Is there any resolution to the problem? Might it help to not add so many Harmony hubs?

Thanks for the help...

**Comment by nicoduj** [comment]
Hi,

I would suggest trying at first with one hub, and with a fixed ip configuration and see if the error occurs. If not, add one more and wait a few days.

**Comment by sddgit** [comment]
Will do. Is this possible bug documented/talked about somewhere, or is it something you’ve observed yourself?

**Comment by nicoduj** [comment]
Hi, I have not observed this problem but I have only one hub. Many users have 2, but very few have more, so it is just a guess and a step by step procedure to analyse your situation :)

**Comment by sddgit** [comment]
I have recently spent a lot more time on this, with considerable success. I now have 5 Harmony hubs running flawlessly since I switched to static IP addresses. I thought I'd document what I set out to do and what I've ended up with, in case anyone else is interested. There is also a request, and a problem report...

**What I wanted to do**
This is, of course, personal preference, but the main thing I wanted to accomplish was a degree of Siri control and automation. I didn't really want to control things from the Home app - the Harmony remote is much better for that. But it's nice to be able to speak commands sometimes. I ended up with this sort of configuration:

            "name": "Lounge",
            "hubIP": "192.168.0.244",
            "TVAccessory": true,
            "mainActivity": "TV",
            "playPauseBehavior": true,
            "numberOfCommandsSentForVolumeControl": 7,
            "switchAccessories": true,
            "activitiesToPublishAsAccessoriesSwitch": [
                "TV",
                "Apple TV",
                "Disc",
                "Roon"
            ],
            "publishGeneralMuteSwitch": true,
            "publishGeneralVolumeSlider": false,
            "publishGeneralVolumeSwitches": true,
            "linkVolumeControlToTV": true,
            "publishSwitchActivitiesAsIndividualAccessories": false,
            "sequencesToPublishAsAccessoriesSwitch": [
                "SEVEN",
                "NINE",
                "TEN",
                "ABC",
                "ABC NEWS"
            ],
            "publishSequencesAsIndividualAccessories": false

I wanted a TV accessory so I can do things like automate lights when the accessory turns on (and to be able to have the control centre remote work if needs be). And then have activities as switches for use mainly by Siri. I have `publishSwitchActivitiesAsIndividualAccessories": false` and `publishSequencesAsIndividualAccessories": false` basically to save clutter. The volume and mute switches end up within the TV accessory, the activities within a group I renamed to TV Inputs, and sequences within a group I renamed to "Channels". Volume switches I renamed to "louder" and "softer", and the mute switch to "mute". The sequences are macros that just enter the appropriate channel numbers.

The names of all the switches need a lot of finessing to keep Siri happy! When you have multiple hubs with similar activities and sequences, you have to somehow differentiate them. Sure, you could say "Lounge Apple TV" and turn on that TV, but if you forget the "Lounge" bit, all the TVs turn on! The same goes for channel changes. So I ended up renaming all the activities to things like "Watch Apple TV Lounge", "Watch TV Lounge" etc. Same for channel changes - "Channel SEVEN Lounge" etc. Now everything seems to work pretty well. I can say:

TV Lounge (to turn on and go to default activity)
Watch TV Lounge
Watch Apple TV Lounge
Louder Lounge
Channel ABC Lounge

**Issues/Requests**
1. The Harmony Alexa skill picks up Harmony favourite channels. This has the advantage that you can say to Alexa "Turn on Channel 7", and, just like what would happen if you tapped on a favourite channel on the remote, the TV turns on first if needs be, and then the channel change takes place. With Siri, I have to say "TV Lounge", wait for it to turn on, then ask for a channel change. I don't know if this is technically feasible.
2. It's a little confusing that when you say "TV Lounge" the TV turns on, but then if you say it again (maybe you forgot which activity you were on), the TV turns off. Do you think there is a way around this? Maybe by having the switches stateless?
3. What does `configureaccesscontrol` do?
4. Not a problem with the plugin, but a Harmony Apple TV activity doesn't give you the option of having the Apple TV control the volume, which the Apple TV does if you're using bluetooth or HomePod speakers. So the volume switches don't work.

**A problem report**
One of my hubs had the same sequences for 2 activities. This caused errors during startup. Sort of fair enough, but after that, I changed the config for some reason, then restarted HB, and I got a recursive error/HB restart loop.

_Log from duplicate sequencies:_
[1/1/[1/1/2021, 6:46:14 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 1b544333-2b0b-46d5-8f2b-a4dabedb4bb4
    at Bridge.Accessory._this.addBridgedAccessory (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:416:15)
    at /Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge/src/server.ts:310:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge/src/server.ts:270:69)
    at Server.start (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge/src/server.ts:158:10)
    at cli (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

_Log when HB kept restarting_
(node:68495) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 009ac407-cf08-456e-9df7-7bb9f3d9fa8b
    at Bridge.Accessory._this.addBridgedAccessory (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:416:15)
    at Bridge.Accessory._this.addBridgedAccessories (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:450:12)
    at Server.handleRegisterPlatformAccessories (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge/src/server.ts:528:17)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.registerPlatformAccessories (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge/src/api.ts:316:10)
    at HarmonyBase.addAccessories (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/harmonyBase.js:1442:25)
    at HarmonyBase.getSequencesAccessories (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/harmonyBase.js:1014:12)
    at HarmonyBase.setupFoundAccessories (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/harmonyBase.js:344:10)
    at HarmonySubPlatform.readAccessories (/Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:173:22)
    at /Users/serveruser/.nvm/versions/node/v14.15.3/lib/node_modules/homebridge-harmony/harmonyBase.js:93:27
(Use `node --trace-warnings ...` to show where the warning was created)
(node:68495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:68495) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Sorry for such a long post. There is a donation on the way - I'm very happy to get all this working!

**Comment by nicoduj** [comment]
Hi,

many thanks for the detail feedback . 

Concerning your problem, I suggest you fill a bug report for that. I should generate a unique id for sequences and not rely on their name since it is indeed not unique.

Concerning your remarks / suggestions :
1/  I don't use tv channels (apple tv based only) , but since alexa can do it I think it is also possible. I will try to see if I can use them and see, but might be  long shot since I don't have any "channel" at home like I said.
2/ In france, I say turn on and turn off, not only the name of the TV accessory. But never found a way to turn it on a specif input however (except of using switches with names, but like you said can be a bit tricky ....
3/ it is an option to enable accessory control in case of home sharing. I only have implemented it like the doc says, but never fully tested it
4/ I use my receiver, but not surprised by that since I think harmony does not handle the apple tv remote .

**Comment by sddgit** [comment]
OK, I will raise a bug report.

1. I guess you could set up a dummy activity and some favourite channels to test. Apart from actually controlling any equipment it should work fine.
4. Are you using the bluetooth version of the Apple TV device (https://support.myharmony.com/en-us/harmony-experience-with-apple-tv#appleTVBT)? It's much better, because it supports the "TV" button and can sleep the Apple TV. With the Apple TV controlling the volume of HomePod speakers, I can go in and re-assign the volume buttons to the Apple TV volume buttons, but that doesn't help the volume switches from your plugin. I'm talking to Harmony about this. I think the Apple TV should be recognised as a device that can control volume and the Harmony volume buttons show be automatically assigned as such.

Donation on the way for all your amazing work...

**Comment by nicoduj** [comment]
Closing this one since the bug issue is opened #333
