### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JacVid** [nicoduj/homebridge-harmony#352]
**Describe the bug**
[06/03/2021, 16:56:26] [Harmony] (Harmony)ERROR (1)- refreshCurrentActivity Error: WebSocket closed with reason: undefined (undefined). - Stack : Error: WebSocket closed with reason: undefined (undefined).
    at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:353:19)
    at WebSocket.listener (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:311:64)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:198:10)
    at Receiver.receiverOnFinish (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:815:20)
    at Receiver.emit (events.js:315:20)
    at finish (internal/streams/writable.js:657:10)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[06/03/2021, 16:56:26] [Harmony] (Harmony)WARNING - socket closed

**Config**
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony",
            "hubIP": "10.0.1.120",
            "cleanCache": false,
            "publishSwitchActivitiesAsIndividualAccessories": false,
            "activitiesToPublishAsAccessoriesSwitch": [
                "Regarder CanalSat",
                "Regarder Apple TV"
            ],
            "switchAccessories": true,
            "TVAccessory": false,
            "showTurnOffActivity": "inverted",
            "activitiesToPublishAsInputForTVMode": [],
            "remoteOverrideCommandsList": [],
            "skippedIfSameStateActivities": [],
            "devicesToPublishAsAccessoriesSwitch": [],
            "sequencesToPublishAsAccessoriesSwitch": [],
            "homeControlsToPublishAsAccessoriesSwitch": [],
            "otherPlatforms": []
        },

**Additional context**
Homebridge v1.3.2

Any idea of the problem which occur randomly.

**Comment by nicoduj** [comment]
Hi, it is a network issue, nothing I can do about it. The socket was closed, if it reopens and works after it means that  it is correctly handled.
If not, check that your hub ip is fixed and that there is no dhcp renewal (every 24H or around that)
