### ISSUE TITLE
Hamony causing Homebridge to shut down under Ubuntu Desktop 20.04

### ISSUE THREAD

**Issue by fiedlerd** [nicoduj/homebridge-harmony#354]
**Describe the bug**
Once Harmony plugin is activated, Homebridge throws the following exception:

Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:108:27)
    at Prober.done (/usr/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)

**My Config**
{
            "name": "Harmony",
            "hubIP": "192.168.178.24",
            "mainActivity": "Fernsehen",
            "platform": "HarmonyHubWebSocket"
        }

**Expected behavior**
Running fine on Raspberry pi on Debian, but behaving buggy on Ubuntu Desktop.
Once Harmony Config is deleted, no exception is thrown.

**Comment by nicoduj** [comment]
Hi, harmony plugin use an external accessory, so it use another port / dns name for discovery . I think the problem is not the plugin, but on mdns stack / homebridge itself . Try to see if it works without tv accessory to confirm please

**Comment by fiedlerd** [comment]
Ty for your reply.

It's weird but now it works with TV Accessory switched on... But it won't show up the code for manual adding Harmony to HomeKit. But I will try out some things now...

**Comment by fiedlerd** [comment]
Never mind, I got it.
But I really don't know why it works now, I only installed a vnc package before, but this cannot fix it right?

**Comment by nicoduj** [comment]
My guess is that you add two homebridge process running or something like that . Rebooting / installing something might have forced the process to quit
