### ISSUE TITLE
Homebridge Crash when turning off activity

### ISSUE THREAD

**Issue by bobybob69** [nicoduj/homebridge-harmony#36]
Hi team 

When turning off activity using the same activity button in the home app, my homebridge crash (see error message bellow) . 

I don't really understand why .. If someone can help me understand the issue ? 

Thanks for your support 

/usr/local/lib/node_modules/homebridge-harmony/index.js:454
                    'Turning on off Activity ' + serviceControl.displayName
                                                                ^
TypeError: Cannot read property 'displayName' of undefined
    at wsp.onUnpackedMessage.addListener.data (/usr/local/lib/node_modules/homebridge-harmony/index.js:454:65)
    at Timeout.apply [as _onTimeout] (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/node_modules/chnl/es5/channel.js:230:1)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

**Comment by nicoduj** [comment]
Hi, seems like a bug, I am investigating since I do'nt have it by my side and don't understand why at first.

**Comment by nicoduj** [comment]
could you post your config file please so that I can check the exact configuration ?

**Comment by nicoduj** [comment]
fix in 0.1.7
