### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Funskes** [nicoduj/homebridge-harmony#364]
I get a red message from Homebridge

![Schermafbeelding 2021-05-18 om 11 10 29](https://user-images.githubusercontent.com/58253773/118627833-56a81700-b7cc-11eb-9771-71f4600e6d1e.jpg)

**Logs**
[09/05/2021, 11:18:11] [Harmony Hub] (Harmony Hub)ERROR (1)- refreshCurrentActivity TypeError: Cannot read property 'result' of undefined - Stack : TypeError: Cannot read property 'result' of undefined
    at /usr/local/lib/node_modules/homebridge-harmony/node_modules/harmony-websocket/lib/harmony-websocket.js:244:45
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[09/05/2021, 11:18:11] [Harmony Hub] (Harmony Hub)ERROR (2)- refreshCurrentActivity TypeError: Cannot read property 'result' of undefined - Stack : TypeError: Cannot read property 'result' of undefined
    at /usr/local/lib/node_modules/homebridge-harmony/node_modules/harmony-websocket/lib/harmony-websocket.js:244:45
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[09/05/2021, 11:18:19] [Harmony Hub] (Harmony Hub)ERROR (3)- refreshCurrentActivity TypeError: Cannot read property 'result' of undefined - Stack : TypeError: Cannot read property 'result' of undefined
    at /usr/local/lib/node_modules/homebridge-harmony/node_modules/harmony-websocket/lib/harmony-websocket.js:244:45
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[09/05/2021, 16:40:48] [Homebridge UI] [homebridge] Failed to check registry.npmjs.org for updates: "timeout of 5000ms exceeded" - see https://git.io/JJSz6 for help.
[09/05/2021, 22:28:59] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[10/05/2021, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[10/05/2021, 02:03:18] [Homebridge UI] Running scheduled instance backup...
[10/05/2021, 02:03:18] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-Mw35Be/homebridge-backup-0EC217786A98.tar.gz
[10/05/2021, 04:22:37] [Homebridge UI] [homebridge] Failed to check registry.npmjs.org for updates: "timeout of 5000ms exceeded" - see https://git.io/JJSz6 for help.
[10/05/2021, 16:24:19] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[10/05/2021, 16:47:10] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[11/05/2021, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[11/05/2021, 02:03:18] [Homebridge UI] Running scheduled instance backup...
[11/05/2021, 02:03:18] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-kVyd0e/homebridge-backup-0EC217786A98.tar.gz
[12/05/2021, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[12/05/2021, 02:03:18] [Homebridge UI] Running scheduled instance backup...
[12/05/2021, 02:03:18] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-8ZTWoi/homebridge-backup-0EC217786A98.tar.gz
[13/05/2021, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[13/05/2021, 02:03:18] [Homebridge UI] Running scheduled instance backup...
[13/05/2021, 02:03:18] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-CEO4Ii/homebridge-backup-0EC217786A98.tar.gz
[13/05/2021, 10:11:42] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[13/05/2021, 16:32:02] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[13/05/2021, 16:32:08] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[14/05/2021, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[14/05/2021, 02:03:18] [Homebridge UI] Running scheduled instance backup...
[14/05/2021, 02:03:18] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-mpONOi/homebridge-backup-0EC217786A98.tar.gz
[15/05/2021, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[15/05/2021, 02:03:18] [Homebridge UI] Running scheduled instance backup...
[15/05/2021, 02:03:18] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-awud8i/homebridge-backup-0EC217786A98.tar.gz
[15/05/2021, 12:11:20] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "socket hang up" - see https://git.io/JJSz6 for help.
[16/05/2021, 00:35:25] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[16/05/2021, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[16/05/2021, 02:03:18] [Homebridge UI] Running scheduled instance backup...
[16/05/2021, 02:03:18] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-YEzRsj/homebridge-backup-0EC217786A98.tar.gz
[16/05/2021, 04:06:35] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[16/05/2021, 04:59:25] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[16/05/2021, 05:48:06] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[16/05/2021, 06:46:46] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[16/05/2021, 21:13:04] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[16/05/2021, 21:13:10] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[16/05/2021, 22:30:27] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[17/05/2021, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[17/05/2021, 02:03:18] [Homebridge UI] Running scheduled instance backup...
[17/05/2021, 02:03:18] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-OWEDGj/homebridge-backup-0EC217786A98.tar.gz
[17/05/2021, 05:14:27] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[17/05/2021, 05:14:33] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[17/05/2021, 06:34:07] [Harmony Hub] (Harmony Hub)WARNING - socket closed
[17/05/2021, 10:34:28] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[17/05/2021, 10:34:34] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[17/05/2021, 17:52:06] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[18/05/2021, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[18/05/2021, 02:03:18] [Homebridge UI] Running scheduled instance backup...
[18/05/2021, 02:03:18] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-i9QvSj/homebridge-backup-0EC217786A98.tar.gz

**Config**
            "name": "Harmony Hub",
            "hubIP": "192.168.2.171",
            "hubName": "Harmony Hub",
            "TVAccessory": false,
            "switchAccessories": true,
            "publishGeneralVolumeSlider": false,
            "publishGeneralVolumeSwitches": false,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "platform": "HarmonyHubWebSocket"

**Additional context**
How can I solve this??

**Comment by nicoduj** [comment]
Hi,

It is network related, the harmony is slow to respond to homebridge / plugin . I see the socket is closed very often. Did you try in a separate bridge in homebridge if not ? Does your hub have some times red light ?

Are you sure your ip is fixed and does  not renew / change sometimes ? You should not use both IP and hubName by the way.

**Comment by Funskes** [comment]
Now I put it in a separate home bridge, so let's wait and see if it gets better now.

The IP address of all my devices is fixed in my router, in addition I have the IP address of the Homebridge also fixed in the Raspberry.

The Harmony hub gets the fixed IP address from my router, but I don't see any possibility to give the Harmony hub a fixed IP address in the app itself, but in my opinion that's not necessary either.

**Comment by Funskes** [comment]
It looks like the separate bridge in Homebridge solved this problem!
Thank you!!
