### ISSUE TITLE
[BUG] Plugin disabled by homebridge due to inability to reach server?

### ISSUE THREAD

**Issue by ericCJessen** [nicoduj/homebridge-harmony#376]
**Describe the bug**

A couple days ago I lost the ability to control Govee devices on homebridge. When I dug into the log today, I saw this:

 [Govee] Disabling HTTP client as connect EHOSTUNREACH 54.164.0.155:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16).
[21/08/2021, 20:52:50] [Govee] Disabling API client as connect EHOSTUNREACH 52.45.27.50:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16).
[21/08/2021, 20:52:50] [Govee] Disabling BLE client as no enabled devices configured.
[21/08/2021, 20:52:50] [Govee] ***** Disabling plugin. *****
[21/08/2021, 20:52:50] [Govee] ***** No devices found to initialise. *****

Is this an error on my side I can fix? It looks like it's connected to the server on the other end. 

**Logs**
Your log in debug mode (-D option)

**Config**
{
    "name": "Govee",
    "username": [email],
    "password": [password],
    "apiKey": [api key],
    "platform": "Govee"
}
**Additional context**

Node.js Version | v14.17.4
-- | --

**Comment by nicoduj** [comment]
Hi,

I think there is a mistake there "govee" is not this harmony plugin .
