### ISSUE TITLE
Websocket issue? [Self-resolved]

### ISSUE THREAD

**Issue by tomlcooper** [nicoduj/homebridge-harmony#382]
My HarmonyHub is reporting 'no response' in the Home app. In the Homebridge logs, I can see errors relating to WebSockets.

**Logs**
[16/11/2021, 09:07:17] [Harmony Hub] (Harmony Hub)ERROR (3)- refreshCurrentActivity Error: WebSocket closed with reason: undefined (undefined). - Stack : Error: WebSocket closed with reason: undefined (undefined).
    at WebSocketAsPromised._handleClose (/usr/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:353:19)
    at WebSocket.listener (/usr/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:311:64)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emitClose (/usr/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:188:12)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:580:15)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[16/11/2021, 09:07:17] [Harmony Hub] (Harmony Hub)WARNING - socket closed

**Config**
 {
            "name": "Harmony Hub",
            "hubIP": "192.168.1.xx",
            "mainActivity": "Watch TV",
            "remoteOverrideCommandsList": [
                {
                    "ActivityName": "Watch TV",
                    "CommandsList": [
                        {
                            "CommandName": "INFORMATION",
                            "NewCommand": "Humax DVR;Guide"
                        }
                    ]
                }
            ],
            "platform": "HarmonyHubWebSocket"
        }

**Comment by tomlcooper** [comment]
This issue seems to have self-resolved. Thank you.
