### ISSUE TITLE
(Harmony)ERROR

### ISSUE THREAD

**Issue by bsoener** [nicoduj/homebridge-harmony#388]
Hello, I always get this error message:

```
[14/01/2022, 12:41:59] [Harmony] (Harmony)WARNING - socket closed
[14/01/2022, 12:42:12] [Harmony] (Harmony)ERROR (5)- refreshCurrentActivity Error: WebSocket closed with reason: undefined (undefined). - Stack : Error: WebSocket closed with reason: undefined (undefined).
    at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:353:19)
    at WebSocket.listener (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:311:64)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emitClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:236:12)
    at emitErrorAndClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:836:13)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:697:5)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
[14/01/2022, 12:42:12] [Harmony] (Harmony)WARNING - socket closed
[14/01/2022, 12:42:22] [Harmony] (Harmony)WARNING - refreshCurrentActivity : NO refresh done since too much socket errors - will retry later
[14/01/2022, 12:43:22] [Harmony] (Harmony)WARNING - refreshCurrentActivity : Resetting counter after network loss, trying to refresh
[14/01/2022, 16:51:58] [Harmony] (Harmony)WARNING - socket closed
```
```

{
            "name": "Harmony",
            "hubIP": "192.168.178.104",
            "hubName": "xxxxxxxxxxx",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": false,
            "TVAccessory": true,
            "configureAccesscontrol": false,
            "platform": "HarmonyHubWebSocket"
        },
```

Hope you can help me where the problem is.

**Comment by nicoduj** [comment]
Hi,
Are you using hoobs ? you can also check your network, and ensure that ip is fixed. Please do not use both IP and hubname, IP is more reliable.

**Comment by bsoener** [comment]
I do not use hoobs. <--homebridge. The ip is fixed and it is also correct. In the setting I have:
-enter name from your hub.
-in the middle tray the ip
-and in the third tray hub name of my app.
What should I delete now?

**Comment by bsoener** [comment]
```
[28/01/2022, 10:53:21] [Harmony] (Harmony)WARNING - socket closed
[28/01/2022, 10:53:35] [Harmony] (Harmony)ERROR (1)- refreshCurrentActivity Error: WebSocket closed with reason: undefined (undefined). - Stack : Error: WebSocket closed with reason: undefined (undefined).
    at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:353:19)
    at WebSocket.listener (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:311:64)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emitClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:236:12)
    at emitErrorAndClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:836:13)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:697:5)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
[28/01/2022, 10:53:35] [Harmony] (Harmony)WARNING - socket closed
[28/01/2022, 10:53:48] [Harmony] (Harmony)ERROR (2)- refreshCurrentActivity Error: WebSocket closed with reason: undefined (undefined). - Stack : Error: WebSocket closed with reason: undefined (undefined).
    at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:353:19)
    at WebSocket.listener (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:311:64)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emitClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:236:12)
    at emitErrorAndClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:836:13)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:697:5)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
[28/01/2022, 10:53:48] [Harmony] (Harmony)WARNING - socket closed
[28/01/2022, 10:54:01] [Harmony] (Harmony)ERROR (3)- refreshCurrentActivity Error: WebSocket closed with reason: undefined (undefined). - Stack : Error: WebSocket closed with reason: undefined (undefined).
    at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:353:19)
    at WebSocket.listener (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:311:64)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emitClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:236:12)
    at emitErrorAndClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:836:13)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:697:5)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
[28/01/2022, 10:54:01] [Harmony] (Harmony)WARNING - socket closed
[28/01/2022, 10:54:14] [Harmony] (Harmony)ERROR (4)- refreshCurrentActivity Error: WebSocket closed with reason: undefined (undefined). - Stack : Error: WebSocket closed with reason: undefined (undefined).
    at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:353:19)
    at WebSocket.listener (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:311:64)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emitClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:236:12)
    at emitErrorAndClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:836:13)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/node_modules/ws/lib/websocket.js:697:5)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
[28/01/2022, 10:54:14] [Harmony] (Harmony)WARNING - socket closed
[28/01/2022, 11:09:36] [Harmony] (Harmony)WARNING - socket closed
[28/01/2022, 11:40:52] [Harmony] (Harmony)WARNING - socket closed
```

**Comment by nicoduj** [comment]
#387 for merging this issue
