### ISSUE TITLE
[BUG] Cannot add service with the same UUID.

### ISSUE THREAD

**Issue by Chrisandersen123** [nicoduj/homebridge-harmony#412]
Hello i get this error over and over again. is there something i have done wrong here or is it somekind of bug?

i keep getting this error code in the log. 

[9/12/2022, 10:29:38 PM] [Harmony Hub] (undefined)INFO - received discovered hubs  xx.x.x.xx|Harmony Hub|15864582
[9/12/2022, 10:29:39 PM] [Harmony Hub] (undefined)INFO - configuring Main TV Service
[9/12/2022, 10:29:39 PM] [Harmony Hub] (undefined)INFO - Creating TV Service
**[9/12/2022, 10:29:39 PM] Error: Cannot add a Service with the same UUID '000000D8-0000-1000-8000-0026BB765291' and subtype 'undefined TV' as another Service in this Accessory.
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:473:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at HarmonySubPlatform.configureMainService (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:406:17)
    at HarmonySubPlatform.readTVAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:248:10)
    at HarmonySubPlatform.readAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:170:58)
    at /usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:107:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)** 
[9/12/2022, 10:29:39 PM] Got SIGTERM, shutting down Homebridge...
[9/12/2022, 10:29:39 PM] [Harmony Hub] INFO - shutdown
[9/12/2022, 10:29:44 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[9/12/2022, 10:29:49 PM] [HB Supervisor] Restarting Homebridge...
[9/12/2022, 10:29:49 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[9/12/2022, 10:29:49 PM] [HB Supervisor] Started Homebridge v1.5.0 with PID: 15496

**Comment by nicoduj** [comment]
Hi,

It seems that there is some problem with cached accessories. Could you try to clean cache or delete accessories through homebridge ui ? Please share your confit also.

**Comment by Chrisandersen123** [comment]
Hi, so cleaning the caches on startup works but then i removes the switches from my homekite automations every time i restart the server. Not a big problem once i get homebridge over on a raspberry pie but is there some way to get around this? dont need the tv to show up cause i can controll the tv from homekit natively.  I cant seen to be able to remove any accsessories through the homebridge UI?

**Comment by nicoduj** [comment]
Hi,
seems strange, there might be some conflict between activity names. Could you share your config and log in debug so I can see the list of devices  ?

you can always use dedicated options however to limit what you want to expose (tV accessory or not, whichc activities you wand to show as switches).

**Comment by nicoduj** [comment]
closing since there was not answer. Please try again if it persist with cleaning cache
