### ISSUE TITLE
[FEATURE] Homebridge 2.0 Support

### ISSUE THREAD

**Issue by scottleestrange** [nicoduj/homebridge-harmony#444]
Hey,

Soon Homebridge 2.0 will be released which will have some breaking changes to plugins.
Could you please check if this plugin is impacted and make it work with 2.0?

https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

**Comment by fromdetroit7** [comment]
I'm not the smartest person but I'm pretty sure this is the lowest of low on dev priority list and don't fix until it's broken which means once 2.0 goes live - and it breaks - it'll be updated. As long as it's eventually updated I'm good but I do have an older TV that requires harmony hub to function with my setup.

**Comment by jabrown93** [comment]
The plugin works fine for me on V2, [PR](https://github.com/nicoduj/homebridge-harmony/pull/445) to update  `package.json` to tell Homebridge it's fine

**Comment by adavison007** [comment]
Homebridge 2.0 is on the way, will you be adding the tick in your code to show it is compatible?

**Comment by adavison007** [comment]
> The plugin works fine for me on V2, [PR](https://github.com/nicoduj/homebridge-harmony/pull/445) to update `package.json` to tell Homebridge it's fine

@jabrown93  Hi, I just installed Homebridge V2.0 Beta 27 and Harmony plugin fails to load, it looks like it is due to the code adding "-" in the naming and the non alpha numeric characters.  It also appears that the channel names come in with non alpha numeric symbols too "/,-,+" etc.

Would you be able to test this and fix please? The plugin works perfectly in Homebridge V1. Thanks in advance, much appreciated

[10/06/2025, 15:31:07] [Lounge Harmony] Child bridge starting (pid 916)...
[10/06/2025, 15:31:07] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[10/06/2025, 15:31:07] [Lounge Harmony] Child bridge started successfully (plugin v1.6.3).
[10/06/2025, 15:31:07] Loaded 0 cached accessories from cachedAccessories.0EC1CEEDF097.
[10/06/2025, 15:31:07] [Lounge Harmony] HarmonyPlatform Init
[10/06/2025, 15:31:07] [Lounge Harmony] DidFinishLaunching
[10/06/2025, 15:31:07] [Lounge Harmony] (Lounge Harmony)INFO - Loading activities...
[10/06/2025, 15:31:07] [Lounge Harmony] (Kitchen Harmony)INFO - Loading activities...
[10/06/2025, 15:31:07] Homebridge v2.0.0-beta.29 (HAP v2.0.0-beta.0) (Lounge Harmony) is running on port 56815.
[10/06/2025, 15:31:08] [Lounge Harmony] (Kitchen Harmony)INFO - Adding Accessory : Kitchen Harmony-TV

/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:244
    myHarmonyAccessory.category = Accessory.Categories.TELEVISION;
                                                       ^
TypeError: Cannot read properties of undefined (reading 'TELEVISION')
    at HarmonySubPlatform.readTVAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:244:56)
    at HarmonySubPlatform.readAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:170:58)
    at /usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:107:27
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[10/06/2025, 15:31:08] [Lounge Harmony] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.
[10/06/2025, 15:31:08] [Lounge Harmony] Child bridge will automatically restart in 10 seconds (restart attempt 1 of 4).
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Sky SciFi/HorHD'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Sky SciFi/HorHD'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Sky SciFi/HorHD'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Nickelodeon+1'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Nickelodeon+1'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Sky SciFi/HorHD'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Sky SciFi/HorHD'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Sky SciFi/HorHD'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
[10/06/2025, 15:31:21] [Lounge Harmony] Child bridge starting (pid 947)...
[10/06/2025, 15:31:21] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[10/06/2025, 15:31:21] [Lounge Harmony] Child bridge started successfully (plugin v1.6.3).
[10/06/2025, 15:31:21] Loaded 0 cached accessories from cachedAccessories.0EC1CEEDF097.
[10/06/2025, 15:31:21] [Lounge Harmony] HarmonyPlatform Init
[10/06/2025, 15:31:21] [Lounge Harmony] DidFinishLaunching
[10/06/2025, 15:31:21] [Lounge Harmony] (Lounge Harmony)INFO - Loading activities...
[10/06/2025, 15:31:21] [Lounge Harmony] (Kitchen Harmony)INFO - Loading activities...
[10/06/2025, 15:31:21] Homebridge v2.0.0-beta.29 (HAP v2.0.0-beta.0) (Lounge Harmony) is running on port 56815.
[10/06/2025, 15:31:22] [Lounge Harmony] (Kitchen Harmony)INFO - Adding Accessory : Kitchen Harmony-TV

/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:244
    myHarmonyAccessory.category = Accessory.Categories.TELEVISION;
                                                       ^
TypeError: Cannot read properties of undefined (reading 'TELEVISION')
    at HarmonySubPlatform.readTVAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:244:56)
    at HarmonySubPlatform.readAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:170:58)
    at /usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:107:27
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[10/06/2025, 15:31:22] [Lounge Harmony] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.

**Comment by adavison007** [comment]
@jabrown93 I'm happy to donate some money via paypal to have this challenge resolved :) please let me know if you are able to assist, thanks.

**Comment by nicoduj** [comment]
Hi, sorry but I am a bit busy right niw, but I will take a look at this as soon as possible .

**Comment by jabrown93** [comment]
@adavison007 the issues you're seeing have been fixed in the code, but a new version needs to be released @nicoduj. The fixes look to be from Sept 2024 and the last release is from May 23.

When running the latest code it's working on v2, but the latest version released to NPM is broken on v2

**Comment by adavison007** [comment]
> [@adavison007](https://github.com/adavison007) the issues you're seeing have been fixed in the code, but a new version needs to be released [@nicoduj](https://github.com/nicoduj). The fixes look to be from Sept 2024 and the last release is from May 23.
> 
> When running the latest code it's working on v2, but the latest version released to NPM is broken on v2

@jabrown93 @nicoduj  thanks, so how do I install the version with the working code? I’m confused? I’ve downloaded the latest version from homebridge… thanks in advance

**Comment by jabrown93** [comment]
@adavison007 to get it the fastest you'd have to clone this GitHub repo to the machine running Homebridge and run `npm i && npm link`

It won't be available as a normal update until @nicoduj releases an update to the NPM registry

**Comment by adavison007** [comment]
> [@adavison007](https://github.com/adavison007) to get it the fastest you'd have to clone this GitHub repo to the machine running Homebridge and run `npm i && npm link`
> 
> It won't be available as a normal update until [@nicoduj](https://github.com/nicoduj) releases an update to the NPM registry

@jabrown93 Thanks for the response, I have no idea how to even start doing that :( .  

@nicoduj If the code is already written, are you able to kindly enable it to be installed via the NPM?? I'm happy to donate some cash to help?? thanks

**Comment by nicoduj** [comment]
i have prepared the code, but travis is not free anymore so pipeline for nom is broken. will take a look for a replacement

**Comment by nicoduj** [comment]
ok, just published it but without any tests ... let me know

**Comment by nicoduj** [comment]
did some tests, lots of things seems broken from previous commits .... Will take some time to fix I think.

**Comment by nicoduj** [comment]
Cool if it works, for me lots of issues with my conf would you mind sharing yours ? The Plugin became quite complex over time with lots of options. 
Concerning donation link, there is no need at all especially since I have not maintain it very well for some time now. However the donate link / PayPal nicoduj is ok and the GitHub sponsor also .

**Comment by adavison007** [comment]
Here's my config...

{
            "name": "Lounge Harmony",
            "hubIP": "XXXXX",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "cleanCache": true,
            "publishAllTVAsExternalAccessory": true,
            "TVAccessory": true,
            "ReceiverIcon": false,
            "sortInput": 2,
            "mainActivity": "Sky TV",
            "otherPlatforms": [
                {
                    "name": "Kitchen Harmony",
                    "hubIP": "XXXXXX",
                    "TVAccessory": true,
                    "ReceiverIcon": false,
                    "sortInput": 2,
                    "mainActivity": "Sky TV"
                }
            ],
            "_bridge": {
                "username": "XXXXXXX",
                "port": 56815
            },
            "platform": "HarmonyHubWebSocket"
        }

**Comment by adavison007** [comment]
OK, done some testing... firstly ignore my comments about channel names, that was a different plugin.. Thanks for the help too.

I have it working, here are the issues..

1) Now when adding two hubs (ensuring child name is correct) you can't add them as seperate accessories, they only get added with the child bridge itself... I rolled back to the previous version on HB 1.0 and the correct behaviour happens so this is an issue with the new bet Harmony code. see photos

2) The inputs from activities in harmony, no longer self populate in the beta code, the previous version they work fine

3) Re point1, you can't get a TV icon anymore with the new code. 

Hope this helps resolve the issues... It stemlike previous fixes are no longer in the new beta code?

<img width="603" alt="Image" src="https://github.com/user-attachments/assets/c8e604d5-89fa-4198-bb89-6fd378946741" />

<img width="603" alt="Image" src="https://github.com/user-attachments/assets/073464ea-77a7-41b1-8adc-35c1673a1b3c" />

**Comment by adavison007** [comment]
Update, If I now select the new receiver option in the config, these can be added as seperate accessories!! but not when set to TV 

<img width="603" alt="Image" src="https://github.com/user-attachments/assets/3a75e486-ad33-4ecc-afea-38a3df69dd62" />

![Image](https://github.com/user-attachments/assets/1643b84d-cbbd-4483-96f1-3cf93f11d750)

**Comment by nicoduj** [comment]
Thanks for the info will use it to narrow the issue . I noticed in your conf you have cleancache set to true : it is not good and should be only set if you have some issue because it will recreate accessoires at each start .

**Comment by adavison007** [comment]
> Thanks for the info will use it to narrow the issue . I noticed in your conf you have cleancache set to true : it is not good and should be only set if you have some issue because it will recreate accessoires at each start .

Thanks, yep, already changed that, only had it selected whilst fixing issues. if you need me to test anything, let me know. Everything worked fine in the previous version, so it seems some old issues have found heir way back in to the 2.0 code somehow.

**Comment by nicoduj** [comment]
Version 1.6.3 was ok ? Think i will rollback evrything to it and start again I have a lot of strange beahviors right now

**Comment by adavison007** [comment]
> Version 1.6.3 was ok ? Think i will rollback evrything to it and start again I have a lot of strange beahviors right now

Yes, 1.3.3 worked perfectly for all features and functions, other than the issue for HB 2.0

**Comment by adavison007** [comment]
> Version 1.6.3 was ok ? Think i will rollback evrything to it and start again I have a lot of strange beahviors right now

Hi @nicoduj Any joy with getting a new version for HB 2.0? Thanks in advance.

**Comment by nicoduj** [comment]
1.6.3 is safer yes. Unfortunately no time to works on hb2 seriously. I have a lot of strange issue as well which makes the new version not easy to do

**Comment by adavison007** [comment]
> 1.6.3 is safer yes. Unfortunately no time to works on hb2 seriously. I have a lot of strange issue as well which makes the new version not easy to do

OK thanks, I'm running the beta and it works well, other than the main issue is the issue with Two harmonies it doesn't see them as accessories and not as TVs, this issue was also in a previous version and was then fixed.. It feels like the Beta version, wasn't;t built off of 1.6.3 which is solid :)

**Comment by nicoduj** [comment]
It was but with an external contributor and I suspect the changes made for homebridge 2 are breaking something arround linked accessoires but can’t figure what right now. NicolasLe 22 juil. 2025 à 11:03, adavison007 ***@***.***> a écrit :﻿adavison007 left a comment (nicoduj/homebridge-harmony#444)

1.6.3 is safer yes. Unfortunately no time to works on hb2 seriously. I have a lot of strange issue as well which makes the new version not easy to do

OK thanks, I'm running the beta and it works well, other than the main issue is the issue with Two harmonies it doesn't see them as accessories and not as TVs, this issue was also in a previous version and was then fixed.. It feels like the Beta version, wasn't;t built off of 1.6.3 which is solid :)

**Comment by nicoduj** [comment]
A beta 4 has been published. You need to remove and add the TV again, generated id changes . Please let me know if it works.

**Comment by adavison007** [comment]
As per the other conversation in the other bug, this "Beta 4" is working perfectly for me now... I had to clear caches and delete and reinstall plug in to remove some gremlins from Beta 2.

**Comment by adavison007** [comment]
@nicoduj All is working well, but just noticed this warning on reboot.... 

**[28/08/2025, 09:30:05]** Loaded plugin: homebridge-harmony@2.0.0-beta4

**[28/08/2025, 09:30:05]** Registering platform 'homebridge-harmony.HarmonyHubWebSocket'

**[28/08/2025, 09:30:05]** The plugin "homebridge-harmony" requires a Homebridge version of ^1.6.0 || ^2.0.0 which does not satisfy the current Homebridge version of v2.0.0-beta.29. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

**Comment by nicoduj** [comment]
Hi, yeah I made it ready for final release of 2.0, but since it is still in beta it is expected and should not be a problem. The waringin should disappear once home bridge is in non beta.

**Comment by danielraffel** [comment]
> Hi, yeah I made it ready for final release of 2.0, but since it is still in beta it is expected and should not be a problem. The waringin should disappear once home bridge is in non beta.

Now that v2 is released are there any plans to update this and release? Thanks for considering. Sounds like there was a build that might've been delayed until HB2.
