### ISSUE TITLE
HarmonyHub - not supported

### ISSUE THREAD

**Issue by petschni** [nicoduj/homebridge-harmony#47]
I am trying out the new support for `TVPlatformMode`. 

The log looks fine in when starting up: 

```
[2/2/2019, 7:07:22 PM] [HarmonyHub] Creating Main TV Service | stdout
-- | --
[2/2/2019, 7:07:22 PM] [HarmonyHub] Initializing platform accessory 'HarmonyHub'...
```

The UI in Home shows "Not Supported" for "HarmonyHub".

And the following error is in the logs:

```
Unhandled rejection TimeoutError: operation timed out
at afterTimeout (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/timers.js:46:19)
at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/timers.js:76:13)
```

**Comment by krazyflipj** [comment]
@petschni are you running iOS 12.2 beta?

**Comment by nicoduj** [comment]
Indeed it seems like you don’t have ios 12.2 beta.

Concerning your error could you give the full log / run in debug mode ?
