### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by RobotLimeLtd** [nicoduj/homebridge-harmony#5]
I'm getting an error when starting up home bridge with this module (see below).  I'm configuring two Harmony Hubs as follows:

```
"platforms": [
    {
        "platform": "HarmonyHub",
        "name": "LivingRoom",
        "hubIP": "192.168.1.10"
    },
    {
        "platform": "HarmonyHub",
        "name": "Kitchen",
        "hubIP": "192.168.1.11"
    },
```

```
/usr/lib/node_modules/homebridge/lib/api.js:122
throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
^
Error: The requested platform 'HarmonyHub' was not registered by any plugin.
at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:314:45)
at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3
homebridge.service: main process exited, code=exited, status=1/FAILURE
Unit homebridge.service entered failed state.
```

**Comment by RobotLimeLtd** [comment]
My package.json is 

`{
  "name": "my-hombridge",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "homebridge": "^0.4.45",
    "homebridge-cmdswitch2": "^0.2.10",
    "homebridge-harmony": "0.0.52",
    "homebridge-nest": "^2.1.4",
    "ajv": "^5.0.0",
    "ps4-waker": "^1.6.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}
`

**Comment by RobotLimeLtd** [comment]
My stupid fault - I had installed the package locally instead of globally.

**Comment by nicoduj** [comment]
Nice if it works ! Don’t hesitate to post if you have some bugs / suggestions !
