### ISSUE TITLE
homebridge failed to start on 0.2.4 upgrade - TypeError: Service.Television is not a constructor

### ISSUE THREAD

**Issue by hire-vladimir** [nicoduj/homebridge-harmony#51]
just upgraded to 0.2.4 release via npm, seeing below on restart of homebridge. 

```
Feb  3 14:28:51 vpie systemd[1]: Started Node.js HomeKit Server.
Feb  3 14:28:53 vpie homebridge[3896]: [2019-2-3 14:28:53] Loaded config.json with 1 accessories and 1 platforms.
Feb  3 14:28:53 vpie homebridge[3896]: [2019-2-3 14:28:53] ---
Feb  3 14:28:54 vpie homebridge[3896]: [2019-2-3 14:28:54] Loaded plugin: homebridge-harmony
Feb  3 14:28:54 vpie homebridge[3896]: [2019-2-3 14:28:54] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
Feb  3 14:28:54 vpie homebridge[3896]: [2019-2-3 14:28:54] ---
Feb  3 14:28:55 vpie homebridge[3896]: [2019-2-3 14:28:55] Loaded plugin: homebridge-thermometer-am2320
Feb  3 14:28:55 vpie homebridge[3896]: [2019-2-3 14:28:55] Registering accessory 'homebridge-am2320.AM2320'
Feb  3 14:28:55 vpie homebridge[3896]: [2019-2-3 14:28:55] ---
Feb  3 14:28:55 vpie homebridge[3896]: [2019-2-3 14:28:55] Loading 1 platforms...
Feb  3 14:28:55 vpie homebridge[3896]: [2019-2-3 14:28:55] [vHarmonyHub] Initializing HarmonyHubWebSocket platform...
Feb  3 14:28:55 vpie homebridge[3896]: [2019-2-3 14:28:55] [vHarmonyHub] PlatformMode : true
Feb  3 14:28:55 vpie homebridge[3896]: [2019-2-3 14:28:55] [vHarmonyHub] Loading activities...
Feb  3 14:28:55 vpie homebridge[3896]: [2019-2-3 14:28:55] Loading 1 accessories...
Feb  3 14:28:55 vpie homebridge[3896]: [2019-2-3 14:28:55] [Sensor] Initializing AM2320 accessory...
Feb  3 14:28:55 vpie homebridge[3896]: AM23280 sensor options: {"i2cBusNo":1,"i2cAddress":92,"temperature":{"rate":1},"humidity":{"rate":1}}
Feb  3 14:28:56 vpie homebridge[3896]: data = {
Feb  3 14:28:56 vpie homebridge[3896]:   "temperature": 20.9,
Feb  3 14:28:56 vpie homebridge[3896]:   "humidity": 27.8
Feb  3 14:28:56 vpie homebridge[3896]: }
Feb  3 14:28:56 vpie homebridge[3896]: [2019-2-3 14:28:56] [vHarmonyHub] Creating Main TV Service
Feb  3 14:28:56 vpie homebridge[3896]: /usr/lib/node_modules/homebridge-harmony/harmonyAsTVPlatform.js:117
Feb  3 14:28:56 vpie homebridge[3896]:       controlService: new Service.Television(that.name, 'tvService'),
Feb  3 14:28:56 vpie homebridge[3896]:                       ^
Feb  3 14:28:56 vpie homebridge[3896]: TypeError: Service.Television is not a constructor
Feb  3 14:28:56 vpie homebridge[3896]:   at HarmonyPlatformAsTVPlatform.readAccessories (/usr/lib/node_modules/homebridge-harmony/harmonyAsTVPlatform.js:117:23)
Feb  3 14:28:56 vpie homebridge[3896]:   at harmonyPlatform.wsp.onUnpackedMessage.addListener.data (/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:283:33)
Feb  3 14:28:56 vpie homebridge[3896]:   at Timeout._onTimeout (/usr/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/dist/index.js:2:4404)
Feb  3 14:28:56 vpie homebridge[3896]:   at ontimeout (timers.js:498:11)
Feb  3 14:28:56 vpie homebridge[3896]:   at tryOnTimeout (timers.js:323:5)
Feb  3 14:28:56 vpie homebridge[3896]:   at Timer.listOnTimeout (timers.js:290:5)
Feb  3 14:28:56 vpie systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Feb  3 14:28:56 vpie systemd[1]: homebridge.service: Unit entered failed state.
Feb  3 14:28:56 vpie systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

homebrige config:

```
"platforms": [

	   {
		"platform": "HarmonyHubWebSocket",
		"name": "HarmonyHub",
		"hubIP": "192.168.20.2",
		"TVPlatformMode" : true,
		"mainActivity" : "Watch Apple TV"
	   }

	]
```

**Comment by nicoduj** [comment]
Hi,

using TVPlatformMode needs homebridge 0.0.46 at least + IOS 12.2 beta !
