### ISSUE TITLE
once added homebridge won't respond 

### ISSUE THREAD

**Issue by roberkane212** [nicoduj/homebridge-harmony#58]
I originally got this plugin to work great with my tcl, however now it won't let any accessories respond once added. if you can help at all please do i really love this plugin plus i only got the hub to do this specifically

**Comment by nicoduj** [comment]
Hi, could you post your logs ? Did you try with version 0.2.7 instead of latest ?

**Comment by roberkane212** [comment]
[2/10/2019, 6:34:37 PM] Loaded config.json with 0 accessories and 1 platforms.
[2/10/2019, 6:34:37 PM] ---
[2/10/2019, 6:34:41 PM] Loaded plugin: homebridge-alexa
[2/10/2019, 6:34:41 PM] Registering platform 'homebridge-alexa.Alexa'
[2/10/2019, 6:34:41 PM] ---
[2/10/2019, 6:34:42 PM] Loaded plugin: homebridge-broadlink-rm
[2/10/2019, 6:34:42 PM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[2/10/2019, 6:34:42 PM] ---
[2/10/2019, 6:34:42 PM] Loaded plugin: homebridge-cmd4
[2/10/2019, 6:34:42 PM] Registering accessory 'homebridge-cmd4.Cmd4'
[2/10/2019, 6:34:42 PM] Registering platform 'homebridge-cmd4.Cmd4'
[2/10/2019, 6:34:42 PM] ---
[2/10/2019, 6:34:42 PM] Loaded plugin: homebridge-cmdswitch2
[2/10/2019, 6:34:42 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[2/10/2019, 6:34:42 PM] ---
[2/10/2019, 6:34:43 PM] Loaded plugin: homebridge-config-ui-x
[2/10/2019, 6:34:43 PM] Registering platform 'homebridge-config-ui-x.config'
[2/10/2019, 6:34:43 PM] ---
[2/10/2019, 6:34:43 PM] Loaded plugin: homebridge-fan-accessory
[2/10/2019, 6:34:43 PM] Registering accessory 'homebridge-fan-accessory.fan-accessory-rotation'
[2/10/2019, 6:34:43 PM] ---
[2/10/2019, 6:34:44 PM] Loaded plugin: homebridge-harmony
[2/10/2019, 6:34:44 PM] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
[2/10/2019, 6:34:44 PM] ---
[2/10/2019, 6:34:45 PM] Loaded plugin: homebridge-roku
homebridge API version: 2.3
[2/10/2019, 6:34:45 PM] Registering accessory 'homebridge-roku.Roku'
[2/10/2019, 6:34:45 PM] ---
[2/10/2019, 6:34:46 PM] Loaded plugin: homebridge-smartthings
[2/10/2019, 6:34:46 PM] Registering platform 'homebridge-smartthings.SmartThings'
[2/10/2019, 6:34:46 PM] ---
[2/10/2019, 6:34:46 PM] ====================
[2/10/2019, 6:34:46 PM] ERROR LOADING PLUGIN homebridge-switchmate3:
[2/10/2019, 6:34:46 PM] Error: Cannot find module 'xpc-connection'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate3/node_modules/noble/lib/mac/highsierra.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate3/node_modules/noble/lib/mac/bindings.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports (/usr/local/lib/node_modules/homebridge-switchmate3/node_modules/noble/lib/resolve-bindings.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate3/node_modules/noble/index.js:2:49)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate3/node_modules/noble-device/lib/util.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate3/node_modules/noble-device/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate3/node_modules/node-switchmate3/lib/Switchmate3Device.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate3/node_modules/node-switchmate3/index.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate3/Switchmate3Manager.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate3/index.js:2:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:23)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:149:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:141:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[2/10/2019, 6:34:46 PM] ====================
[2/10/2019, 6:34:47 PM] Loaded plugin: homebridge-tplink-smarthome
[2/10/2019, 6:34:47 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[2/10/2019, 6:34:47 PM] ---
[2/10/2019, 6:34:47 PM] Loading 1 platforms...
[2/10/2019, 6:34:47 PM] [harmonyhub] Initializing HarmonyHubWebSocket platform...
[2/10/2019, 6:34:47 PM] [harmonyhub] PlatformMode : true
[2/10/2019, 6:34:47 PM] [harmonyhub] Loading activities...
Load homebridge-cmdswitch2.cmdSwitch2
Load homebridge-tplink-smarthome.TplinkSmarthome
[2/10/2019, 6:34:47 PM] [homebridge-tplink-smarthome.TplinkSmarthome] homebridge-tplink-smarthome v3.11.0, node v10.13.0, homebridge v0.4.46
[2/10/2019, 6:34:47 PM] [homebridge-tplink-smarthome.TplinkSmarthome] Configuring cached accessory: [Closet Light] 8012A106DD9A4AD8042576E37A182E2318D0E1EB e1008ab0-3936-418c-9ebb-a52c38a2d670
[2/10/2019, 6:34:48 PM] [harmonyhub] Creating Main TV Service
[2/10/2019, 6:34:48 PM] [harmonyhub] Creating InputSourceService Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Mute for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping VolumeDown for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping VolumeUp for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionDown for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionLeft for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionRight for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionUp for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Select for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Play for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Rewind for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Pause for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping FastForward for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Return for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Home for Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Creating InputSourceService PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Mute for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping VolumeDown for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping VolumeUp for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionDown for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionLeft for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionRight for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionUp for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Select for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Play for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Rewind for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Pause for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping FastForward for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Return for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Home for PS4
[2/10/2019, 6:34:48 PM] [harmonyhub] Creating InputSourceService Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Mute for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping VolumeDown for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping VolumeUp for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionDown for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionLeft for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionRight for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionUp for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Select for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Play for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Rewind for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Pause for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping FastForward for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Return for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Home for Apple TV
[2/10/2019, 6:34:48 PM] [harmonyhub] Creating InputSourceService HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Mute for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping VolumeDown for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping VolumeUp for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionDown for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionLeft for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionRight for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionUp for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Select for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Play for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Rewind for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Pause for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping FastForward for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Return for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Home for HDMI 3
[2/10/2019, 6:34:48 PM] [harmonyhub] Creating InputSourceService Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Mute for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping VolumeDown for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping VolumeUp for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionDown for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionLeft for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionRight for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping DirectionUp for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Select for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Play for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Rewind for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Pause for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping FastForward for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] Mapping Return for Netflix
[2/10/2019, 6:34:48 PM] [harmonyhub] WARNING - No main Activity that match config file found, default to first one
[2/10/2019, 6:34:48 PM] [harmonyhub] Configuring Main Activity Cable
[2/10/2019, 6:34:48 PM] [harmonyhub] Creating TV Speaker Service
[2/10/2019, 6:34:48 PM] [harmonyhub] Adding Accessory : harmonyhub
[2/10/2019, 6:34:48 PM] [harmonyhub] Initializing platform accessory 'harmonyhub'...
Setup Payload:
X-HM://0023ISYWZ16P0
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-155 │     
    └────────────┘

**Comment by roberkane212** [comment]
{
	"bridge": {
		"name": "HomeBridgePi",
		"username": "CC:22:3D:E3:CE:33",
		"port": 51826,
		"pin": "031-44-154"
	},
	"platforms": [{
		"platform": "HarmonyHubWebSocket",
		"name": "harmonyhub",
		"hubIP": "192.168.0.24",
		"TVPlatformMode": true,
		"mainActivity": " LA TV"
	}]
}

**Comment by nicoduj** [comment]
Thank you.

First, just in case, you've got a plugin that fails to start : homebridge-switchmate3 . could you try disable it ?

Then, your main activity is not correct : "mainActivity": " LA TV"
-> should be one of your activities: Apple TV, PS4, Netflix, HDMI 3, Cable

Could you try with those modifications ?
You can also try with latest version I published this morning, might help.

**Comment by roberkane212** [comment]
Well the reason its failing is because i deleted out of config just to see if the one plugin will work. will try what you recommended. yes i am on 12.2 like i said when i used it the first time it worked great then just started failing

**Comment by roberkane212** [comment]
It works for a second then goes to no response

**Comment by roberkane212** [comment]
[tv] INFO - onMessage : Refreshing activity to -1
[2/11/2019, 5:19:58 AM] [tv] INFO - onMessage : Refreshing activity to 38341857

**Comment by roberkane212** [comment]
tried to update and got this error

pi@raspberrypi:~ $ sudo npm i homebridge-harmony
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/nicoduj/harmony-websocket.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-11T10_25_11_229Z-debug.log

**Comment by nicoduj** [comment]
Got is not found. Since the changes I made are not yet accepted by the maintainer of a dependency I had to reference my gut instead .

**Comment by roberkane212** [comment]
So what do I do now??

**Comment by nicoduj** [comment]
You have several options ;) : 
 - install git,
- wait for the maintainer to accept my pull request ( https://github.com/lopelex/harmony-websocket/pull/3) and me to publish again
- Install 0.2.7
- Install 0.2.7 and manually update with sources of my repo + sources of my fork of the lib : https://github.com/nicoduj/harmony-websocket 

However, I am not sure the no response is really linked to this. No one else brought this issue. Did you try to empty your cash folder on homebridge / delete and add again ? Not responding in home app is also sometime due to hub problems (Apple TV or Homepod), and sometimes disconnecting them / rebooting and/or removing / re-adding them into your home might help.

**Comment by roberkane212** [comment]
2.7? Of what plugin?

**Comment by nicoduj** [comment]
Hi,

I said 0.2.7. Of this very same plugin : https://github.com/nicoduj/homebridge-harmony/tree/0.2.7 .
This version was not using the external library which might be the reason of your problem.

**Comment by roberkane212** [comment]
I don’t see a 0.2.7 I have 0.3.9 unless I have the wrong plugin

**Comment by nicoduj** [comment]
https://github.com/nicoduj/homebridge-harmony/tree/0.2.7

**Comment by roberkane212** [comment]
still getting error

sudo npm install -g homebridge-harmony
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b master git://github.com/nicoduj/harmony-websocket.git /root/.npm/_cacache/tmp/git-clone-3f6508b4
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-3f6508b4': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-12T21_25_49_590Z-debug.log

**Comment by nicoduj** [comment]
Take a look at #60

**Comment by roberkane212** [comment]
Got it working on my Mac, won’t update on my RPi

**Comment by nicoduj** [comment]
Like I said, it is an issue with the git config I think and the fact that a dependency is not a published npm package. You will have to wait for the maintainer of the package to accept my pull request / publish the dependency.

**Comment by nicoduj** [comment]
Back to official dependency in 0.3.91 so it should solve this issue

**Comment by roberkane212** [comment]
any advice on this error?

/usr/bin/homebridge-roku-config -> /usr/lib/node_modules/homebridge-roku/bin/setup

> curve25519-n@1.4.0 install /usr/lib/node_modules/homebridge-roku/node_modules/curve25519-n
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "/path/to/executable/python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-roku/node_modules/curve25519-n
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-15T20_36_03_434Z-debug.log

**Comment by roberkane212** [comment]
sorry wrong page
